// Code generated by ent, DO NOT EDIT.

package storagelocation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the storagelocation type in the database.
	Label = "storage_location"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFolderName holds the string denoting the foldername field in the database.
	FieldFolderName = "folderName"
	// FieldPartCount holds the string denoting the partcount field in the database.
	FieldPartCount = "partCount"
	// FieldMergeStartedAt holds the string denoting the mergestartedat field in the database.
	FieldMergeStartedAt = "mergeStartedAt"
	// FieldMergedAt holds the string denoting the mergedat field in the database.
	FieldMergedAt = "mergedAt"
	// FieldMaterializationUnsupportedAt holds the string denoting the materializationunsupportedat field in the database.
	FieldMaterializationUnsupportedAt = "materializationUnsupportedAt"
	// FieldPartsDeletedAt holds the string denoting the partsdeletedat field in the database.
	FieldPartsDeletedAt = "partsDeletedAt"
	// FieldLastDownloadedAt holds the string denoting the lastdownloadedat field in the database.
	FieldLastDownloadedAt = "lastDownloadedAt"
	// EdgeCacheEntries holds the string denoting the cacheentries edge name in mutations.
	EdgeCacheEntries = "cacheEntries"
	// Table holds the table name of the storagelocation in the database.
	Table = "storage_locations"
	// CacheEntriesTable is the table that holds the cacheEntries relation/edge.
	CacheEntriesTable = "cache_entries"
	// CacheEntriesInverseTable is the table name for the CacheEntry entity.
	// It exists in this package in order to avoid circular dependency with the "cacheentry" package.
	CacheEntriesInverseTable = "cache_entries"
	// CacheEntriesColumn is the table column denoting the cacheEntries relation/edge.
	CacheEntriesColumn = "locationId"
)

// Columns holds all SQL columns for storagelocation fields.
var Columns = []string{
	FieldID,
	FieldFolderName,
	FieldPartCount,
	FieldMergeStartedAt,
	FieldMergedAt,
	FieldMaterializationUnsupportedAt,
	FieldPartsDeletedAt,
	FieldLastDownloadedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FolderNameValidator is a validator for the "folderName" field. It is called by the builders before save.
	FolderNameValidator func(string) error
	// PartCountValidator is a validator for the "partCount" field. It is called by the builders before save.
	PartCountValidator func(int) error
)

// OrderOption defines the ordering options for the StorageLocation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFolderName orders the results by the folderName field.
func ByFolderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFolderName, opts...).ToFunc()
}

// ByPartCount orders the results by the partCount field.
func ByPartCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPartCount, opts...).ToFunc()
}

// ByMergeStartedAt orders the results by the mergeStartedAt field.
func ByMergeStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMergeStartedAt, opts...).ToFunc()
}

// ByMergedAt orders the results by the mergedAt field.
func ByMergedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMergedAt, opts...).ToFunc()
}

// ByMaterializationUnsupportedAt orders the results by the materializationUnsupportedAt field.
func ByMaterializationUnsupportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaterializationUnsupportedAt, opts...).ToFunc()
}

// ByPartsDeletedAt orders the results by the partsDeletedAt field.
func ByPartsDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPartsDeletedAt, opts...).ToFunc()
}

// ByLastDownloadedAt orders the results by the lastDownloadedAt field.
func ByLastDownloadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDownloadedAt, opts...).ToFunc()
}

// ByCacheEntriesCount orders the results by cacheEntries count.
func ByCacheEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCacheEntriesStep(), opts...)
	}
}

// ByCacheEntries orders the results by cacheEntries terms.
func ByCacheEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCacheEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCacheEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CacheEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CacheEntriesTable, CacheEntriesColumn),
	)
}
