// Code generated by ent, DO NOT EDIT.

package storagelocation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldContainsFold(FieldID, id))
}

// FolderName applies equality check predicate on the "folderName" field. It's identical to FolderNameEQ.
func FolderName(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldFolderName, v))
}

// PartCount applies equality check predicate on the "partCount" field. It's identical to PartCountEQ.
func PartCount(v int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldPartCount, v))
}

// SizeBytes applies equality check predicate on the "sizeBytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldSizeBytes, v))
}

// LeaseVersion applies equality check predicate on the "leaseVersion" field. It's identical to LeaseVersionEQ.
func LeaseVersion(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldLeaseVersion, v))
}

// DeletionRequestedAt applies equality check predicate on the "deletionRequestedAt" field. It's identical to DeletionRequestedAtEQ.
func DeletionRequestedAt(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldDeletionRequestedAt, v))
}

// MergeStartedAt applies equality check predicate on the "mergeStartedAt" field. It's identical to MergeStartedAtEQ.
func MergeStartedAt(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergeStartedAt, v))
}

// MergeLeaseToken applies equality check predicate on the "mergeLeaseToken" field. It's identical to MergeLeaseTokenEQ.
func MergeLeaseToken(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergeLeaseToken, v))
}

// MergeLeaseExpiresAt applies equality check predicate on the "mergeLeaseExpiresAt" field. It's identical to MergeLeaseExpiresAtEQ.
func MergeLeaseExpiresAt(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergeLeaseExpiresAt, v))
}

// MergedAt applies equality check predicate on the "mergedAt" field. It's identical to MergedAtEQ.
func MergedAt(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergedAt, v))
}

// MaterializationUnsupportedAt applies equality check predicate on the "materializationUnsupportedAt" field. It's identical to MaterializationUnsupportedAtEQ.
func MaterializationUnsupportedAt(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMaterializationUnsupportedAt, v))
}

// PartsDeletedAt applies equality check predicate on the "partsDeletedAt" field. It's identical to PartsDeletedAtEQ.
func PartsDeletedAt(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldPartsDeletedAt, v))
}

// LastDownloadedAt applies equality check predicate on the "lastDownloadedAt" field. It's identical to LastDownloadedAtEQ.
func LastDownloadedAt(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldLastDownloadedAt, v))
}

// FolderNameEQ applies the EQ predicate on the "folderName" field.
func FolderNameEQ(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldFolderName, v))
}

// FolderNameNEQ applies the NEQ predicate on the "folderName" field.
func FolderNameNEQ(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldFolderName, v))
}

// FolderNameIn applies the In predicate on the "folderName" field.
func FolderNameIn(vs ...string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldFolderName, vs...))
}

// FolderNameNotIn applies the NotIn predicate on the "folderName" field.
func FolderNameNotIn(vs ...string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldFolderName, vs...))
}

// FolderNameGT applies the GT predicate on the "folderName" field.
func FolderNameGT(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldFolderName, v))
}

// FolderNameGTE applies the GTE predicate on the "folderName" field.
func FolderNameGTE(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldFolderName, v))
}

// FolderNameLT applies the LT predicate on the "folderName" field.
func FolderNameLT(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldFolderName, v))
}

// FolderNameLTE applies the LTE predicate on the "folderName" field.
func FolderNameLTE(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldFolderName, v))
}

// FolderNameContains applies the Contains predicate on the "folderName" field.
func FolderNameContains(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldContains(FieldFolderName, v))
}

// FolderNameHasPrefix applies the HasPrefix predicate on the "folderName" field.
func FolderNameHasPrefix(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldHasPrefix(FieldFolderName, v))
}

// FolderNameHasSuffix applies the HasSuffix predicate on the "folderName" field.
func FolderNameHasSuffix(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldHasSuffix(FieldFolderName, v))
}

// FolderNameEqualFold applies the EqualFold predicate on the "folderName" field.
func FolderNameEqualFold(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEqualFold(FieldFolderName, v))
}

// FolderNameContainsFold applies the ContainsFold predicate on the "folderName" field.
func FolderNameContainsFold(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldContainsFold(FieldFolderName, v))
}

// PartCountEQ applies the EQ predicate on the "partCount" field.
func PartCountEQ(v int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldPartCount, v))
}

// PartCountNEQ applies the NEQ predicate on the "partCount" field.
func PartCountNEQ(v int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldPartCount, v))
}

// PartCountIn applies the In predicate on the "partCount" field.
func PartCountIn(vs ...int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldPartCount, vs...))
}

// PartCountNotIn applies the NotIn predicate on the "partCount" field.
func PartCountNotIn(vs ...int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldPartCount, vs...))
}

// PartCountGT applies the GT predicate on the "partCount" field.
func PartCountGT(v int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldPartCount, v))
}

// PartCountGTE applies the GTE predicate on the "partCount" field.
func PartCountGTE(v int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldPartCount, v))
}

// PartCountLT applies the LT predicate on the "partCount" field.
func PartCountLT(v int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldPartCount, v))
}

// PartCountLTE applies the LTE predicate on the "partCount" field.
func PartCountLTE(v int) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldPartCount, v))
}

// SizeBytesEQ applies the EQ predicate on the "sizeBytes" field.
func SizeBytesEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "sizeBytes" field.
func SizeBytesNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "sizeBytes" field.
func SizeBytesIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "sizeBytes" field.
func SizeBytesNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "sizeBytes" field.
func SizeBytesGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "sizeBytes" field.
func SizeBytesGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "sizeBytes" field.
func SizeBytesLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "sizeBytes" field.
func SizeBytesLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldSizeBytes, v))
}

// SizeBytesIsNil applies the IsNil predicate on the "sizeBytes" field.
func SizeBytesIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldSizeBytes))
}

// SizeBytesNotNil applies the NotNil predicate on the "sizeBytes" field.
func SizeBytesNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldSizeBytes))
}

// LeaseVersionEQ applies the EQ predicate on the "leaseVersion" field.
func LeaseVersionEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldLeaseVersion, v))
}

// LeaseVersionNEQ applies the NEQ predicate on the "leaseVersion" field.
func LeaseVersionNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldLeaseVersion, v))
}

// LeaseVersionIn applies the In predicate on the "leaseVersion" field.
func LeaseVersionIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldLeaseVersion, vs...))
}

// LeaseVersionNotIn applies the NotIn predicate on the "leaseVersion" field.
func LeaseVersionNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldLeaseVersion, vs...))
}

// LeaseVersionGT applies the GT predicate on the "leaseVersion" field.
func LeaseVersionGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldLeaseVersion, v))
}

// LeaseVersionGTE applies the GTE predicate on the "leaseVersion" field.
func LeaseVersionGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldLeaseVersion, v))
}

// LeaseVersionLT applies the LT predicate on the "leaseVersion" field.
func LeaseVersionLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldLeaseVersion, v))
}

// LeaseVersionLTE applies the LTE predicate on the "leaseVersion" field.
func LeaseVersionLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldLeaseVersion, v))
}

// DeletionRequestedAtEQ applies the EQ predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldDeletionRequestedAt, v))
}

// DeletionRequestedAtNEQ applies the NEQ predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldDeletionRequestedAt, v))
}

// DeletionRequestedAtIn applies the In predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldDeletionRequestedAt, vs...))
}

// DeletionRequestedAtNotIn applies the NotIn predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldDeletionRequestedAt, vs...))
}

// DeletionRequestedAtGT applies the GT predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldDeletionRequestedAt, v))
}

// DeletionRequestedAtGTE applies the GTE predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldDeletionRequestedAt, v))
}

// DeletionRequestedAtLT applies the LT predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldDeletionRequestedAt, v))
}

// DeletionRequestedAtLTE applies the LTE predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldDeletionRequestedAt, v))
}

// DeletionRequestedAtIsNil applies the IsNil predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldDeletionRequestedAt))
}

// DeletionRequestedAtNotNil applies the NotNil predicate on the "deletionRequestedAt" field.
func DeletionRequestedAtNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldDeletionRequestedAt))
}

// MergeStartedAtEQ applies the EQ predicate on the "mergeStartedAt" field.
func MergeStartedAtEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergeStartedAt, v))
}

// MergeStartedAtNEQ applies the NEQ predicate on the "mergeStartedAt" field.
func MergeStartedAtNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldMergeStartedAt, v))
}

// MergeStartedAtIn applies the In predicate on the "mergeStartedAt" field.
func MergeStartedAtIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldMergeStartedAt, vs...))
}

// MergeStartedAtNotIn applies the NotIn predicate on the "mergeStartedAt" field.
func MergeStartedAtNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldMergeStartedAt, vs...))
}

// MergeStartedAtGT applies the GT predicate on the "mergeStartedAt" field.
func MergeStartedAtGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldMergeStartedAt, v))
}

// MergeStartedAtGTE applies the GTE predicate on the "mergeStartedAt" field.
func MergeStartedAtGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldMergeStartedAt, v))
}

// MergeStartedAtLT applies the LT predicate on the "mergeStartedAt" field.
func MergeStartedAtLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldMergeStartedAt, v))
}

// MergeStartedAtLTE applies the LTE predicate on the "mergeStartedAt" field.
func MergeStartedAtLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldMergeStartedAt, v))
}

// MergeStartedAtIsNil applies the IsNil predicate on the "mergeStartedAt" field.
func MergeStartedAtIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldMergeStartedAt))
}

// MergeStartedAtNotNil applies the NotNil predicate on the "mergeStartedAt" field.
func MergeStartedAtNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldMergeStartedAt))
}

// MergeLeaseTokenEQ applies the EQ predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenEQ(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenNEQ applies the NEQ predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenNEQ(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenIn applies the In predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenIn(vs ...string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldMergeLeaseToken, vs...))
}

// MergeLeaseTokenNotIn applies the NotIn predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenNotIn(vs ...string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldMergeLeaseToken, vs...))
}

// MergeLeaseTokenGT applies the GT predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenGT(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenGTE applies the GTE predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenGTE(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenLT applies the LT predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenLT(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenLTE applies the LTE predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenLTE(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenContains applies the Contains predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenContains(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldContains(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenHasPrefix applies the HasPrefix predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenHasPrefix(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldHasPrefix(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenHasSuffix applies the HasSuffix predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenHasSuffix(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldHasSuffix(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenIsNil applies the IsNil predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldMergeLeaseToken))
}

// MergeLeaseTokenNotNil applies the NotNil predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldMergeLeaseToken))
}

// MergeLeaseTokenEqualFold applies the EqualFold predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenEqualFold(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEqualFold(FieldMergeLeaseToken, v))
}

// MergeLeaseTokenContainsFold applies the ContainsFold predicate on the "mergeLeaseToken" field.
func MergeLeaseTokenContainsFold(v string) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldContainsFold(FieldMergeLeaseToken, v))
}

// MergeLeaseExpiresAtEQ applies the EQ predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergeLeaseExpiresAt, v))
}

// MergeLeaseExpiresAtNEQ applies the NEQ predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldMergeLeaseExpiresAt, v))
}

// MergeLeaseExpiresAtIn applies the In predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldMergeLeaseExpiresAt, vs...))
}

// MergeLeaseExpiresAtNotIn applies the NotIn predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldMergeLeaseExpiresAt, vs...))
}

// MergeLeaseExpiresAtGT applies the GT predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldMergeLeaseExpiresAt, v))
}

// MergeLeaseExpiresAtGTE applies the GTE predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldMergeLeaseExpiresAt, v))
}

// MergeLeaseExpiresAtLT applies the LT predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldMergeLeaseExpiresAt, v))
}

// MergeLeaseExpiresAtLTE applies the LTE predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldMergeLeaseExpiresAt, v))
}

// MergeLeaseExpiresAtIsNil applies the IsNil predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldMergeLeaseExpiresAt))
}

// MergeLeaseExpiresAtNotNil applies the NotNil predicate on the "mergeLeaseExpiresAt" field.
func MergeLeaseExpiresAtNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldMergeLeaseExpiresAt))
}

// MergedAtEQ applies the EQ predicate on the "mergedAt" field.
func MergedAtEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMergedAt, v))
}

// MergedAtNEQ applies the NEQ predicate on the "mergedAt" field.
func MergedAtNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldMergedAt, v))
}

// MergedAtIn applies the In predicate on the "mergedAt" field.
func MergedAtIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldMergedAt, vs...))
}

// MergedAtNotIn applies the NotIn predicate on the "mergedAt" field.
func MergedAtNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldMergedAt, vs...))
}

// MergedAtGT applies the GT predicate on the "mergedAt" field.
func MergedAtGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldMergedAt, v))
}

// MergedAtGTE applies the GTE predicate on the "mergedAt" field.
func MergedAtGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldMergedAt, v))
}

// MergedAtLT applies the LT predicate on the "mergedAt" field.
func MergedAtLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldMergedAt, v))
}

// MergedAtLTE applies the LTE predicate on the "mergedAt" field.
func MergedAtLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldMergedAt, v))
}

// MergedAtIsNil applies the IsNil predicate on the "mergedAt" field.
func MergedAtIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldMergedAt))
}

// MergedAtNotNil applies the NotNil predicate on the "mergedAt" field.
func MergedAtNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldMergedAt))
}

// MaterializationUnsupportedAtEQ applies the EQ predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldMaterializationUnsupportedAt, v))
}

// MaterializationUnsupportedAtNEQ applies the NEQ predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldMaterializationUnsupportedAt, v))
}

// MaterializationUnsupportedAtIn applies the In predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldMaterializationUnsupportedAt, vs...))
}

// MaterializationUnsupportedAtNotIn applies the NotIn predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldMaterializationUnsupportedAt, vs...))
}

// MaterializationUnsupportedAtGT applies the GT predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldMaterializationUnsupportedAt, v))
}

// MaterializationUnsupportedAtGTE applies the GTE predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldMaterializationUnsupportedAt, v))
}

// MaterializationUnsupportedAtLT applies the LT predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldMaterializationUnsupportedAt, v))
}

// MaterializationUnsupportedAtLTE applies the LTE predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldMaterializationUnsupportedAt, v))
}

// MaterializationUnsupportedAtIsNil applies the IsNil predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldMaterializationUnsupportedAt))
}

// MaterializationUnsupportedAtNotNil applies the NotNil predicate on the "materializationUnsupportedAt" field.
func MaterializationUnsupportedAtNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldMaterializationUnsupportedAt))
}

// PartsDeletedAtEQ applies the EQ predicate on the "partsDeletedAt" field.
func PartsDeletedAtEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldPartsDeletedAt, v))
}

// PartsDeletedAtNEQ applies the NEQ predicate on the "partsDeletedAt" field.
func PartsDeletedAtNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldPartsDeletedAt, v))
}

// PartsDeletedAtIn applies the In predicate on the "partsDeletedAt" field.
func PartsDeletedAtIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldPartsDeletedAt, vs...))
}

// PartsDeletedAtNotIn applies the NotIn predicate on the "partsDeletedAt" field.
func PartsDeletedAtNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldPartsDeletedAt, vs...))
}

// PartsDeletedAtGT applies the GT predicate on the "partsDeletedAt" field.
func PartsDeletedAtGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldPartsDeletedAt, v))
}

// PartsDeletedAtGTE applies the GTE predicate on the "partsDeletedAt" field.
func PartsDeletedAtGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldPartsDeletedAt, v))
}

// PartsDeletedAtLT applies the LT predicate on the "partsDeletedAt" field.
func PartsDeletedAtLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldPartsDeletedAt, v))
}

// PartsDeletedAtLTE applies the LTE predicate on the "partsDeletedAt" field.
func PartsDeletedAtLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldPartsDeletedAt, v))
}

// PartsDeletedAtIsNil applies the IsNil predicate on the "partsDeletedAt" field.
func PartsDeletedAtIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldPartsDeletedAt))
}

// PartsDeletedAtNotNil applies the NotNil predicate on the "partsDeletedAt" field.
func PartsDeletedAtNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldPartsDeletedAt))
}

// LastDownloadedAtEQ applies the EQ predicate on the "lastDownloadedAt" field.
func LastDownloadedAtEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldEQ(FieldLastDownloadedAt, v))
}

// LastDownloadedAtNEQ applies the NEQ predicate on the "lastDownloadedAt" field.
func LastDownloadedAtNEQ(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNEQ(FieldLastDownloadedAt, v))
}

// LastDownloadedAtIn applies the In predicate on the "lastDownloadedAt" field.
func LastDownloadedAtIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIn(FieldLastDownloadedAt, vs...))
}

// LastDownloadedAtNotIn applies the NotIn predicate on the "lastDownloadedAt" field.
func LastDownloadedAtNotIn(vs ...int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotIn(FieldLastDownloadedAt, vs...))
}

// LastDownloadedAtGT applies the GT predicate on the "lastDownloadedAt" field.
func LastDownloadedAtGT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGT(FieldLastDownloadedAt, v))
}

// LastDownloadedAtGTE applies the GTE predicate on the "lastDownloadedAt" field.
func LastDownloadedAtGTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldGTE(FieldLastDownloadedAt, v))
}

// LastDownloadedAtLT applies the LT predicate on the "lastDownloadedAt" field.
func LastDownloadedAtLT(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLT(FieldLastDownloadedAt, v))
}

// LastDownloadedAtLTE applies the LTE predicate on the "lastDownloadedAt" field.
func LastDownloadedAtLTE(v int64) predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldLTE(FieldLastDownloadedAt, v))
}

// LastDownloadedAtIsNil applies the IsNil predicate on the "lastDownloadedAt" field.
func LastDownloadedAtIsNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldIsNull(FieldLastDownloadedAt))
}

// LastDownloadedAtNotNil applies the NotNil predicate on the "lastDownloadedAt" field.
func LastDownloadedAtNotNil() predicate.StorageLocation {
	return predicate.StorageLocation(sql.FieldNotNull(FieldLastDownloadedAt))
}

// HasCacheEntries applies the HasEdge predicate on the "cacheEntries" edge.
func HasCacheEntries() predicate.StorageLocation {
	return predicate.StorageLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CacheEntriesTable, CacheEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCacheEntriesWith applies the HasEdge predicate on the "cacheEntries" edge with a given conditions (other predicates).
func HasCacheEntriesWith(preds ...predicate.CacheEntry) predicate.StorageLocation {
	return predicate.StorageLocation(func(s *sql.Selector) {
		step := newCacheEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReaderLeases applies the HasEdge predicate on the "readerLeases" edge.
func HasReaderLeases() predicate.StorageLocation {
	return predicate.StorageLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReaderLeasesTable, ReaderLeasesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReaderLeasesWith applies the HasEdge predicate on the "readerLeases" edge with a given conditions (other predicates).
func HasReaderLeasesWith(preds ...predicate.StorageReaderLease) predicate.StorageLocation {
	return predicate.StorageLocation(func(s *sql.Selector) {
		step := newReaderLeasesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StorageLocation) predicate.StorageLocation {
	return predicate.StorageLocation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StorageLocation) predicate.StorageLocation {
	return predicate.StorageLocation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StorageLocation) predicate.StorageLocation {
	return predicate.StorageLocation(sql.NotPredicates(p))
}
