// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/cacheentry"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
)

// CacheEntryUpdate is the builder for updating CacheEntry entities.
type CacheEntryUpdate struct {
	config
	hooks    []Hook
	mutation *CacheEntryMutation
}

// Where appends a list predicates to the CacheEntryUpdate builder.
func (_u *CacheEntryUpdate) Where(ps ...predicate.CacheEntry) *CacheEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *CacheEntryUpdate) SetKey(v string) *CacheEntryUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *CacheEntryUpdate) SetNillableKey(v *string) *CacheEntryUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CacheEntryUpdate) SetVersion(v string) *CacheEntryUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CacheEntryUpdate) SetNillableVersion(v *string) *CacheEntryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *CacheEntryUpdate) SetScope(v string) *CacheEntryUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *CacheEntryUpdate) SetNillableScope(v *string) *CacheEntryUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetRepoId sets the "repoId" field.
func (_u *CacheEntryUpdate) SetRepoId(v string) *CacheEntryUpdate {
	_u.mutation.SetRepoId(v)
	return _u
}

// SetNillableRepoId sets the "repoId" field if the given value is not nil.
func (_u *CacheEntryUpdate) SetNillableRepoId(v *string) *CacheEntryUpdate {
	if v != nil {
		_u.SetRepoId(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *CacheEntryUpdate) SetUpdatedAt(v int64) *CacheEntryUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_u *CacheEntryUpdate) SetNillableUpdatedAt(v *int64) *CacheEntryUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updatedAt" field.
func (_u *CacheEntryUpdate) AddUpdatedAt(v int64) *CacheEntryUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetLocationId sets the "locationId" field.
func (_u *CacheEntryUpdate) SetLocationId(v string) *CacheEntryUpdate {
	_u.mutation.SetLocationId(v)
	return _u
}

// SetNillableLocationId sets the "locationId" field if the given value is not nil.
func (_u *CacheEntryUpdate) SetNillableLocationId(v *string) *CacheEntryUpdate {
	if v != nil {
		_u.SetLocationId(*v)
	}
	return _u
}

// SetLocationID sets the "location" edge to the StorageLocation entity by ID.
func (_u *CacheEntryUpdate) SetLocationID(id string) *CacheEntryUpdate {
	_u.mutation.SetLocationID(id)
	return _u
}

// SetLocation sets the "location" edge to the StorageLocation entity.
func (_u *CacheEntryUpdate) SetLocation(v *StorageLocation) *CacheEntryUpdate {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the CacheEntryMutation object of the builder.
func (_u *CacheEntryUpdate) Mutation() *CacheEntryMutation {
	return _u.mutation
}

// ClearLocation clears the "location" edge to the StorageLocation entity.
func (_u *CacheEntryUpdate) ClearLocation() *CacheEntryUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CacheEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CacheEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CacheEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CacheEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CacheEntryUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := cacheentry.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := cacheentry.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := cacheentry.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoId(); ok {
		if err := cacheentry.RepoIdValidator(v); err != nil {
			return &ValidationError{Name: "repoId", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.repoId": %w`, err)}
		}
	}
	if _u.mutation.LocationCleared() && len(_u.mutation.LocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CacheEntry.location"`)
	}
	return nil
}

func (_u *CacheEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cacheentry.Table, cacheentry.Columns, sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(cacheentry.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(cacheentry.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(cacheentry.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoId(); ok {
		_spec.SetField(cacheentry.FieldRepoId, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cacheentry.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(cacheentry.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cacheentry.LocationTable,
			Columns: []string{cacheentry.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cacheentry.LocationTable,
			Columns: []string{cacheentry.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cacheentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CacheEntryUpdateOne is the builder for updating a single CacheEntry entity.
type CacheEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CacheEntryMutation
}

// SetKey sets the "key" field.
func (_u *CacheEntryUpdateOne) SetKey(v string) *CacheEntryUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *CacheEntryUpdateOne) SetNillableKey(v *string) *CacheEntryUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CacheEntryUpdateOne) SetVersion(v string) *CacheEntryUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CacheEntryUpdateOne) SetNillableVersion(v *string) *CacheEntryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *CacheEntryUpdateOne) SetScope(v string) *CacheEntryUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *CacheEntryUpdateOne) SetNillableScope(v *string) *CacheEntryUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetRepoId sets the "repoId" field.
func (_u *CacheEntryUpdateOne) SetRepoId(v string) *CacheEntryUpdateOne {
	_u.mutation.SetRepoId(v)
	return _u
}

// SetNillableRepoId sets the "repoId" field if the given value is not nil.
func (_u *CacheEntryUpdateOne) SetNillableRepoId(v *string) *CacheEntryUpdateOne {
	if v != nil {
		_u.SetRepoId(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *CacheEntryUpdateOne) SetUpdatedAt(v int64) *CacheEntryUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_u *CacheEntryUpdateOne) SetNillableUpdatedAt(v *int64) *CacheEntryUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updatedAt" field.
func (_u *CacheEntryUpdateOne) AddUpdatedAt(v int64) *CacheEntryUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetLocationId sets the "locationId" field.
func (_u *CacheEntryUpdateOne) SetLocationId(v string) *CacheEntryUpdateOne {
	_u.mutation.SetLocationId(v)
	return _u
}

// SetNillableLocationId sets the "locationId" field if the given value is not nil.
func (_u *CacheEntryUpdateOne) SetNillableLocationId(v *string) *CacheEntryUpdateOne {
	if v != nil {
		_u.SetLocationId(*v)
	}
	return _u
}

// SetLocationID sets the "location" edge to the StorageLocation entity by ID.
func (_u *CacheEntryUpdateOne) SetLocationID(id string) *CacheEntryUpdateOne {
	_u.mutation.SetLocationID(id)
	return _u
}

// SetLocation sets the "location" edge to the StorageLocation entity.
func (_u *CacheEntryUpdateOne) SetLocation(v *StorageLocation) *CacheEntryUpdateOne {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the CacheEntryMutation object of the builder.
func (_u *CacheEntryUpdateOne) Mutation() *CacheEntryMutation {
	return _u.mutation
}

// ClearLocation clears the "location" edge to the StorageLocation entity.
func (_u *CacheEntryUpdateOne) ClearLocation() *CacheEntryUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// Where appends a list predicates to the CacheEntryUpdate builder.
func (_u *CacheEntryUpdateOne) Where(ps ...predicate.CacheEntry) *CacheEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CacheEntryUpdateOne) Select(field string, fields ...string) *CacheEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CacheEntry entity.
func (_u *CacheEntryUpdateOne) Save(ctx context.Context) (*CacheEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CacheEntryUpdateOne) SaveX(ctx context.Context) *CacheEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CacheEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CacheEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CacheEntryUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := cacheentry.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := cacheentry.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := cacheentry.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoId(); ok {
		if err := cacheentry.RepoIdValidator(v); err != nil {
			return &ValidationError{Name: "repoId", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.repoId": %w`, err)}
		}
	}
	if _u.mutation.LocationCleared() && len(_u.mutation.LocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CacheEntry.location"`)
	}
	return nil
}

func (_u *CacheEntryUpdateOne) sqlSave(ctx context.Context) (_node *CacheEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cacheentry.Table, cacheentry.Columns, sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CacheEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cacheentry.FieldID)
		for _, f := range fields {
			if !cacheentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cacheentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(cacheentry.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(cacheentry.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(cacheentry.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoId(); ok {
		_spec.SetField(cacheentry.FieldRepoId, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cacheentry.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(cacheentry.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cacheentry.LocationTable,
			Columns: []string{cacheentry.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cacheentry.LocationTable,
			Columns: []string{cacheentry.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CacheEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cacheentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
