// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/cacheentry"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
)

// CacheEntry is the model entity for the CacheEntry schema.
type CacheEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// RepoId holds the value of the "repoId" field.
	RepoId string `json:"repoId,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt int64 `json:"updatedAt,omitempty"`
	// LocationId holds the value of the "locationId" field.
	LocationId string `json:"locationId,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CacheEntryQuery when eager-loading is set.
	Edges        CacheEntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CacheEntryEdges holds the relations/edges for other nodes in the graph.
type CacheEntryEdges struct {
	// Location holds the value of the location edge.
	Location *StorageLocation `json:"location,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CacheEntryEdges) LocationOrErr() (*StorageLocation, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: storagelocation.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CacheEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cacheentry.FieldUpdatedAt:
			values[i] = new(sql.NullInt64)
		case cacheentry.FieldID, cacheentry.FieldKey, cacheentry.FieldVersion, cacheentry.FieldScope, cacheentry.FieldRepoId, cacheentry.FieldLocationId:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CacheEntry fields.
func (_m *CacheEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cacheentry.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case cacheentry.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case cacheentry.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case cacheentry.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case cacheentry.FieldRepoId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repoId", values[i])
			} else if value.Valid {
				_m.RepoId = value.String
			}
		case cacheentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Int64
			}
		case cacheentry.FieldLocationId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locationId", values[i])
			} else if value.Valid {
				_m.LocationId = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CacheEntry.
// This includes values selected through modifiers, order, etc.
func (_m *CacheEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLocation queries the "location" edge of the CacheEntry entity.
func (_m *CacheEntry) QueryLocation() *StorageLocationQuery {
	return NewCacheEntryClient(_m.config).QueryLocation(_m)
}

// Update returns a builder for updating this CacheEntry.
// Note that you need to call CacheEntry.Unwrap() before calling this method if this CacheEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CacheEntry) Update() *CacheEntryUpdateOne {
	return NewCacheEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CacheEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CacheEntry) Unwrap() *CacheEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CacheEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CacheEntry) String() string {
	var builder strings.Builder
	builder.WriteString("CacheEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("repoId=")
	builder.WriteString(_m.RepoId)
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("locationId=")
	builder.WriteString(_m.LocationId)
	builder.WriteByte(')')
	return builder.String()
}

// CacheEntries is a parsable slice of CacheEntry.
type CacheEntries []*CacheEntry
