// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/cacheentry"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
)

// CacheEntryCreate is the builder for creating a CacheEntry entity.
type CacheEntryCreate struct {
	config
	mutation *CacheEntryMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *CacheEntryCreate) SetKey(v string) *CacheEntryCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *CacheEntryCreate) SetVersion(v string) *CacheEntryCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *CacheEntryCreate) SetScope(v string) *CacheEntryCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetRepoId sets the "repoId" field.
func (_c *CacheEntryCreate) SetRepoId(v string) *CacheEntryCreate {
	_c.mutation.SetRepoId(v)
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *CacheEntryCreate) SetUpdatedAt(v int64) *CacheEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetLocationId sets the "locationId" field.
func (_c *CacheEntryCreate) SetLocationId(v string) *CacheEntryCreate {
	_c.mutation.SetLocationId(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CacheEntryCreate) SetID(v string) *CacheEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetLocationID sets the "location" edge to the StorageLocation entity by ID.
func (_c *CacheEntryCreate) SetLocationID(id string) *CacheEntryCreate {
	_c.mutation.SetLocationID(id)
	return _c
}

// SetLocation sets the "location" edge to the StorageLocation entity.
func (_c *CacheEntryCreate) SetLocation(v *StorageLocation) *CacheEntryCreate {
	return _c.SetLocationID(v.ID)
}

// Mutation returns the CacheEntryMutation object of the builder.
func (_c *CacheEntryCreate) Mutation() *CacheEntryMutation {
	return _c.mutation
}

// Save creates the CacheEntry in the database.
func (_c *CacheEntryCreate) Save(ctx context.Context) (*CacheEntry, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CacheEntryCreate) SaveX(ctx context.Context) *CacheEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CacheEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CacheEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CacheEntryCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "CacheEntry.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := cacheentry.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "CacheEntry.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := cacheentry.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "CacheEntry.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := cacheentry.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepoId(); !ok {
		return &ValidationError{Name: "repoId", err: errors.New(`ent: missing required field "CacheEntry.repoId"`)}
	}
	if v, ok := _c.mutation.RepoId(); ok {
		if err := cacheentry.RepoIdValidator(v); err != nil {
			return &ValidationError{Name: "repoId", err: fmt.Errorf(`ent: validator failed for field "CacheEntry.repoId": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "CacheEntry.updatedAt"`)}
	}
	if _, ok := _c.mutation.LocationId(); !ok {
		return &ValidationError{Name: "locationId", err: errors.New(`ent: missing required field "CacheEntry.locationId"`)}
	}
	if len(_c.mutation.LocationIDs()) == 0 {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required edge "CacheEntry.location"`)}
	}
	return nil
}

func (_c *CacheEntryCreate) sqlSave(ctx context.Context) (*CacheEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CacheEntry.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CacheEntryCreate) createSpec() (*CacheEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &CacheEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cacheentry.Table, sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(cacheentry.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(cacheentry.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(cacheentry.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.RepoId(); ok {
		_spec.SetField(cacheentry.FieldRepoId, field.TypeString, value)
		_node.RepoId = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cacheentry.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cacheentry.LocationTable,
			Columns: []string{cacheentry.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LocationId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CacheEntryCreateBulk is the builder for creating many CacheEntry entities in bulk.
type CacheEntryCreateBulk struct {
	config
	err      error
	builders []*CacheEntryCreate
}

// Save creates the CacheEntry entities in the database.
func (_c *CacheEntryCreateBulk) Save(ctx context.Context) ([]*CacheEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CacheEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CacheEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CacheEntryCreateBulk) SaveX(ctx context.Context) []*CacheEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CacheEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CacheEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
