// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/cacheentry"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagedeletion"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/upload"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CacheEntry is the client for interacting with the CacheEntry builders.
	CacheEntry *CacheEntryClient
	// StorageDeletion is the client for interacting with the StorageDeletion builders.
	StorageDeletion *StorageDeletionClient
	// StorageLocation is the client for interacting with the StorageLocation builders.
	StorageLocation *StorageLocationClient
	// Upload is the client for interacting with the Upload builders.
	Upload *UploadClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CacheEntry = NewCacheEntryClient(c.config)
	c.StorageDeletion = NewStorageDeletionClient(c.config)
	c.StorageLocation = NewStorageLocationClient(c.config)
	c.Upload = NewUploadClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		CacheEntry:      NewCacheEntryClient(cfg),
		StorageDeletion: NewStorageDeletionClient(cfg),
		StorageLocation: NewStorageLocationClient(cfg),
		Upload:          NewUploadClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		CacheEntry:      NewCacheEntryClient(cfg),
		StorageDeletion: NewStorageDeletionClient(cfg),
		StorageLocation: NewStorageLocationClient(cfg),
		Upload:          NewUploadClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CacheEntry.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CacheEntry.Use(hooks...)
	c.StorageDeletion.Use(hooks...)
	c.StorageLocation.Use(hooks...)
	c.Upload.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.CacheEntry.Intercept(interceptors...)
	c.StorageDeletion.Intercept(interceptors...)
	c.StorageLocation.Intercept(interceptors...)
	c.Upload.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CacheEntryMutation:
		return c.CacheEntry.mutate(ctx, m)
	case *StorageDeletionMutation:
		return c.StorageDeletion.mutate(ctx, m)
	case *StorageLocationMutation:
		return c.StorageLocation.mutate(ctx, m)
	case *UploadMutation:
		return c.Upload.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CacheEntryClient is a client for the CacheEntry schema.
type CacheEntryClient struct {
	config
}

// NewCacheEntryClient returns a client for the CacheEntry from the given config.
func NewCacheEntryClient(c config) *CacheEntryClient {
	return &CacheEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cacheentry.Hooks(f(g(h())))`.
func (c *CacheEntryClient) Use(hooks ...Hook) {
	c.hooks.CacheEntry = append(c.hooks.CacheEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cacheentry.Intercept(f(g(h())))`.
func (c *CacheEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.CacheEntry = append(c.inters.CacheEntry, interceptors...)
}

// Create returns a builder for creating a CacheEntry entity.
func (c *CacheEntryClient) Create() *CacheEntryCreate {
	mutation := newCacheEntryMutation(c.config, OpCreate)
	return &CacheEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CacheEntry entities.
func (c *CacheEntryClient) CreateBulk(builders ...*CacheEntryCreate) *CacheEntryCreateBulk {
	return &CacheEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CacheEntryClient) MapCreateBulk(slice any, setFunc func(*CacheEntryCreate, int)) *CacheEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CacheEntryCreateBulk{err: fmt.Errorf("calling to CacheEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CacheEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CacheEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CacheEntry.
func (c *CacheEntryClient) Update() *CacheEntryUpdate {
	mutation := newCacheEntryMutation(c.config, OpUpdate)
	return &CacheEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CacheEntryClient) UpdateOne(_m *CacheEntry) *CacheEntryUpdateOne {
	mutation := newCacheEntryMutation(c.config, OpUpdateOne, withCacheEntry(_m))
	return &CacheEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CacheEntryClient) UpdateOneID(id string) *CacheEntryUpdateOne {
	mutation := newCacheEntryMutation(c.config, OpUpdateOne, withCacheEntryID(id))
	return &CacheEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CacheEntry.
func (c *CacheEntryClient) Delete() *CacheEntryDelete {
	mutation := newCacheEntryMutation(c.config, OpDelete)
	return &CacheEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CacheEntryClient) DeleteOne(_m *CacheEntry) *CacheEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CacheEntryClient) DeleteOneID(id string) *CacheEntryDeleteOne {
	builder := c.Delete().Where(cacheentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CacheEntryDeleteOne{builder}
}

// Query returns a query builder for CacheEntry.
func (c *CacheEntryClient) Query() *CacheEntryQuery {
	return &CacheEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCacheEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a CacheEntry entity by its id.
func (c *CacheEntryClient) Get(ctx context.Context, id string) (*CacheEntry, error) {
	return c.Query().Where(cacheentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CacheEntryClient) GetX(ctx context.Context, id string) *CacheEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLocation queries the location edge of a CacheEntry.
func (c *CacheEntryClient) QueryLocation(_m *CacheEntry) *StorageLocationQuery {
	query := (&StorageLocationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(cacheentry.Table, cacheentry.FieldID, id),
			sqlgraph.To(storagelocation.Table, storagelocation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cacheentry.LocationTable, cacheentry.LocationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CacheEntryClient) Hooks() []Hook {
	return c.hooks.CacheEntry
}

// Interceptors returns the client interceptors.
func (c *CacheEntryClient) Interceptors() []Interceptor {
	return c.inters.CacheEntry
}

func (c *CacheEntryClient) mutate(ctx context.Context, m *CacheEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CacheEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CacheEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CacheEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CacheEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CacheEntry mutation op: %q", m.Op())
	}
}

// StorageDeletionClient is a client for the StorageDeletion schema.
type StorageDeletionClient struct {
	config
}

// NewStorageDeletionClient returns a client for the StorageDeletion from the given config.
func NewStorageDeletionClient(c config) *StorageDeletionClient {
	return &StorageDeletionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `storagedeletion.Hooks(f(g(h())))`.
func (c *StorageDeletionClient) Use(hooks ...Hook) {
	c.hooks.StorageDeletion = append(c.hooks.StorageDeletion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `storagedeletion.Intercept(f(g(h())))`.
func (c *StorageDeletionClient) Intercept(interceptors ...Interceptor) {
	c.inters.StorageDeletion = append(c.inters.StorageDeletion, interceptors...)
}

// Create returns a builder for creating a StorageDeletion entity.
func (c *StorageDeletionClient) Create() *StorageDeletionCreate {
	mutation := newStorageDeletionMutation(c.config, OpCreate)
	return &StorageDeletionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StorageDeletion entities.
func (c *StorageDeletionClient) CreateBulk(builders ...*StorageDeletionCreate) *StorageDeletionCreateBulk {
	return &StorageDeletionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StorageDeletionClient) MapCreateBulk(slice any, setFunc func(*StorageDeletionCreate, int)) *StorageDeletionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StorageDeletionCreateBulk{err: fmt.Errorf("calling to StorageDeletionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StorageDeletionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StorageDeletionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StorageDeletion.
func (c *StorageDeletionClient) Update() *StorageDeletionUpdate {
	mutation := newStorageDeletionMutation(c.config, OpUpdate)
	return &StorageDeletionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StorageDeletionClient) UpdateOne(_m *StorageDeletion) *StorageDeletionUpdateOne {
	mutation := newStorageDeletionMutation(c.config, OpUpdateOne, withStorageDeletion(_m))
	return &StorageDeletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StorageDeletionClient) UpdateOneID(id int64) *StorageDeletionUpdateOne {
	mutation := newStorageDeletionMutation(c.config, OpUpdateOne, withStorageDeletionID(id))
	return &StorageDeletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StorageDeletion.
func (c *StorageDeletionClient) Delete() *StorageDeletionDelete {
	mutation := newStorageDeletionMutation(c.config, OpDelete)
	return &StorageDeletionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StorageDeletionClient) DeleteOne(_m *StorageDeletion) *StorageDeletionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StorageDeletionClient) DeleteOneID(id int64) *StorageDeletionDeleteOne {
	builder := c.Delete().Where(storagedeletion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StorageDeletionDeleteOne{builder}
}

// Query returns a query builder for StorageDeletion.
func (c *StorageDeletionClient) Query() *StorageDeletionQuery {
	return &StorageDeletionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStorageDeletion},
		inters: c.Interceptors(),
	}
}

// Get returns a StorageDeletion entity by its id.
func (c *StorageDeletionClient) Get(ctx context.Context, id int64) (*StorageDeletion, error) {
	return c.Query().Where(storagedeletion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StorageDeletionClient) GetX(ctx context.Context, id int64) *StorageDeletion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *StorageDeletionClient) Hooks() []Hook {
	return c.hooks.StorageDeletion
}

// Interceptors returns the client interceptors.
func (c *StorageDeletionClient) Interceptors() []Interceptor {
	return c.inters.StorageDeletion
}

func (c *StorageDeletionClient) mutate(ctx context.Context, m *StorageDeletionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StorageDeletionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StorageDeletionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StorageDeletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StorageDeletionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown StorageDeletion mutation op: %q", m.Op())
	}
}

// StorageLocationClient is a client for the StorageLocation schema.
type StorageLocationClient struct {
	config
}

// NewStorageLocationClient returns a client for the StorageLocation from the given config.
func NewStorageLocationClient(c config) *StorageLocationClient {
	return &StorageLocationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `storagelocation.Hooks(f(g(h())))`.
func (c *StorageLocationClient) Use(hooks ...Hook) {
	c.hooks.StorageLocation = append(c.hooks.StorageLocation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `storagelocation.Intercept(f(g(h())))`.
func (c *StorageLocationClient) Intercept(interceptors ...Interceptor) {
	c.inters.StorageLocation = append(c.inters.StorageLocation, interceptors...)
}

// Create returns a builder for creating a StorageLocation entity.
func (c *StorageLocationClient) Create() *StorageLocationCreate {
	mutation := newStorageLocationMutation(c.config, OpCreate)
	return &StorageLocationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StorageLocation entities.
func (c *StorageLocationClient) CreateBulk(builders ...*StorageLocationCreate) *StorageLocationCreateBulk {
	return &StorageLocationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StorageLocationClient) MapCreateBulk(slice any, setFunc func(*StorageLocationCreate, int)) *StorageLocationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StorageLocationCreateBulk{err: fmt.Errorf("calling to StorageLocationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StorageLocationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StorageLocationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StorageLocation.
func (c *StorageLocationClient) Update() *StorageLocationUpdate {
	mutation := newStorageLocationMutation(c.config, OpUpdate)
	return &StorageLocationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StorageLocationClient) UpdateOne(_m *StorageLocation) *StorageLocationUpdateOne {
	mutation := newStorageLocationMutation(c.config, OpUpdateOne, withStorageLocation(_m))
	return &StorageLocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StorageLocationClient) UpdateOneID(id string) *StorageLocationUpdateOne {
	mutation := newStorageLocationMutation(c.config, OpUpdateOne, withStorageLocationID(id))
	return &StorageLocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StorageLocation.
func (c *StorageLocationClient) Delete() *StorageLocationDelete {
	mutation := newStorageLocationMutation(c.config, OpDelete)
	return &StorageLocationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StorageLocationClient) DeleteOne(_m *StorageLocation) *StorageLocationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StorageLocationClient) DeleteOneID(id string) *StorageLocationDeleteOne {
	builder := c.Delete().Where(storagelocation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StorageLocationDeleteOne{builder}
}

// Query returns a query builder for StorageLocation.
func (c *StorageLocationClient) Query() *StorageLocationQuery {
	return &StorageLocationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStorageLocation},
		inters: c.Interceptors(),
	}
}

// Get returns a StorageLocation entity by its id.
func (c *StorageLocationClient) Get(ctx context.Context, id string) (*StorageLocation, error) {
	return c.Query().Where(storagelocation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StorageLocationClient) GetX(ctx context.Context, id string) *StorageLocation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCacheEntries queries the cacheEntries edge of a StorageLocation.
func (c *StorageLocationClient) QueryCacheEntries(_m *StorageLocation) *CacheEntryQuery {
	query := (&CacheEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(storagelocation.Table, storagelocation.FieldID, id),
			sqlgraph.To(cacheentry.Table, cacheentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, storagelocation.CacheEntriesTable, storagelocation.CacheEntriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StorageLocationClient) Hooks() []Hook {
	return c.hooks.StorageLocation
}

// Interceptors returns the client interceptors.
func (c *StorageLocationClient) Interceptors() []Interceptor {
	return c.inters.StorageLocation
}

func (c *StorageLocationClient) mutate(ctx context.Context, m *StorageLocationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StorageLocationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StorageLocationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StorageLocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StorageLocationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown StorageLocation mutation op: %q", m.Op())
	}
}

// UploadClient is a client for the Upload schema.
type UploadClient struct {
	config
}

// NewUploadClient returns a client for the Upload from the given config.
func NewUploadClient(c config) *UploadClient {
	return &UploadClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `upload.Hooks(f(g(h())))`.
func (c *UploadClient) Use(hooks ...Hook) {
	c.hooks.Upload = append(c.hooks.Upload, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `upload.Intercept(f(g(h())))`.
func (c *UploadClient) Intercept(interceptors ...Interceptor) {
	c.inters.Upload = append(c.inters.Upload, interceptors...)
}

// Create returns a builder for creating a Upload entity.
func (c *UploadClient) Create() *UploadCreate {
	mutation := newUploadMutation(c.config, OpCreate)
	return &UploadCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Upload entities.
func (c *UploadClient) CreateBulk(builders ...*UploadCreate) *UploadCreateBulk {
	return &UploadCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UploadClient) MapCreateBulk(slice any, setFunc func(*UploadCreate, int)) *UploadCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UploadCreateBulk{err: fmt.Errorf("calling to UploadClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UploadCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UploadCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Upload.
func (c *UploadClient) Update() *UploadUpdate {
	mutation := newUploadMutation(c.config, OpUpdate)
	return &UploadUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UploadClient) UpdateOne(_m *Upload) *UploadUpdateOne {
	mutation := newUploadMutation(c.config, OpUpdateOne, withUpload(_m))
	return &UploadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UploadClient) UpdateOneID(id int64) *UploadUpdateOne {
	mutation := newUploadMutation(c.config, OpUpdateOne, withUploadID(id))
	return &UploadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Upload.
func (c *UploadClient) Delete() *UploadDelete {
	mutation := newUploadMutation(c.config, OpDelete)
	return &UploadDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UploadClient) DeleteOne(_m *Upload) *UploadDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UploadClient) DeleteOneID(id int64) *UploadDeleteOne {
	builder := c.Delete().Where(upload.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UploadDeleteOne{builder}
}

// Query returns a query builder for Upload.
func (c *UploadClient) Query() *UploadQuery {
	return &UploadQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUpload},
		inters: c.Interceptors(),
	}
}

// Get returns a Upload entity by its id.
func (c *UploadClient) Get(ctx context.Context, id int64) (*Upload, error) {
	return c.Query().Where(upload.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UploadClient) GetX(ctx context.Context, id int64) *Upload {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UploadClient) Hooks() []Hook {
	return c.hooks.Upload
}

// Interceptors returns the client interceptors.
func (c *UploadClient) Interceptors() []Interceptor {
	return c.inters.Upload
}

func (c *UploadClient) mutate(ctx context.Context, m *UploadMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UploadCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UploadUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UploadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UploadDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Upload mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CacheEntry, StorageDeletion, StorageLocation, Upload []ent.Hook
	}
	inters struct {
		CacheEntry, StorageDeletion, StorageLocation, Upload []ent.Interceptor
	}
)
