// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/cacheentry"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/schema"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagedeletion"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/upload"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cacheentryFields := schema.CacheEntry{}.Fields()
	_ = cacheentryFields
	// cacheentryDescKey is the schema descriptor for key field.
	cacheentryDescKey := cacheentryFields[1].Descriptor()
	// cacheentry.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	cacheentry.KeyValidator = func() func(string) error {
		validators := cacheentryDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cacheentryDescVersion is the schema descriptor for version field.
	cacheentryDescVersion := cacheentryFields[2].Descriptor()
	// cacheentry.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	cacheentry.VersionValidator = func() func(string) error {
		validators := cacheentryDescVersion.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(version string) error {
			for _, fn := range fns {
				if err := fn(version); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cacheentryDescScope is the schema descriptor for scope field.
	cacheentryDescScope := cacheentryFields[3].Descriptor()
	// cacheentry.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	cacheentry.ScopeValidator = func() func(string) error {
		validators := cacheentryDescScope.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scope string) error {
			for _, fn := range fns {
				if err := fn(scope); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cacheentryDescRepoId is the schema descriptor for repoId field.
	cacheentryDescRepoId := cacheentryFields[4].Descriptor()
	// cacheentry.RepoIdValidator is a validator for the "repoId" field. It is called by the builders before save.
	cacheentry.RepoIdValidator = func() func(string) error {
		validators := cacheentryDescRepoId.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(repoId string) error {
			for _, fn := range fns {
				if err := fn(repoId); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	storagedeletionFields := schema.StorageDeletion{}.Fields()
	_ = storagedeletionFields
	// storagedeletionDescFolderName is the schema descriptor for folderName field.
	storagedeletionDescFolderName := storagedeletionFields[1].Descriptor()
	// storagedeletion.FolderNameValidator is a validator for the "folderName" field. It is called by the builders before save.
	storagedeletion.FolderNameValidator = storagedeletionDescFolderName.Validators[0].(func(string) error)
	// storagedeletionDescAttemptCount is the schema descriptor for attemptCount field.
	storagedeletionDescAttemptCount := storagedeletionFields[3].Descriptor()
	// storagedeletion.DefaultAttemptCount holds the default value on creation for the attemptCount field.
	storagedeletion.DefaultAttemptCount = storagedeletionDescAttemptCount.Default.(int)
	// storagedeletion.AttemptCountValidator is a validator for the "attemptCount" field. It is called by the builders before save.
	storagedeletion.AttemptCountValidator = storagedeletionDescAttemptCount.Validators[0].(func(int) error)
	storagelocationFields := schema.StorageLocation{}.Fields()
	_ = storagelocationFields
	// storagelocationDescFolderName is the schema descriptor for folderName field.
	storagelocationDescFolderName := storagelocationFields[1].Descriptor()
	// storagelocation.FolderNameValidator is a validator for the "folderName" field. It is called by the builders before save.
	storagelocation.FolderNameValidator = storagelocationDescFolderName.Validators[0].(func(string) error)
	// storagelocationDescPartCount is the schema descriptor for partCount field.
	storagelocationDescPartCount := storagelocationFields[2].Descriptor()
	// storagelocation.PartCountValidator is a validator for the "partCount" field. It is called by the builders before save.
	storagelocation.PartCountValidator = storagelocationDescPartCount.Validators[0].(func(int) error)
	uploadFields := schema.Upload{}.Fields()
	_ = uploadFields
	// uploadDescKey is the schema descriptor for key field.
	uploadDescKey := uploadFields[1].Descriptor()
	// upload.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	upload.KeyValidator = func() func(string) error {
		validators := uploadDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadDescVersion is the schema descriptor for version field.
	uploadDescVersion := uploadFields[2].Descriptor()
	// upload.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	upload.VersionValidator = func() func(string) error {
		validators := uploadDescVersion.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(version string) error {
			for _, fn := range fns {
				if err := fn(version); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadDescScope is the schema descriptor for scope field.
	uploadDescScope := uploadFields[3].Descriptor()
	// upload.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	upload.ScopeValidator = func() func(string) error {
		validators := uploadDescScope.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scope string) error {
			for _, fn := range fns {
				if err := fn(scope); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadDescRepoId is the schema descriptor for repoId field.
	uploadDescRepoId := uploadFields[4].Descriptor()
	// upload.RepoIdValidator is a validator for the "repoId" field. It is called by the builders before save.
	upload.RepoIdValidator = func() func(string) error {
		validators := uploadDescRepoId.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(repoId string) error {
			for _, fn := range fns {
				if err := fn(repoId); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadDescStartedPartUploadCount is the schema descriptor for startedPartUploadCount field.
	uploadDescStartedPartUploadCount := uploadFields[7].Descriptor()
	// upload.DefaultStartedPartUploadCount holds the default value on creation for the startedPartUploadCount field.
	upload.DefaultStartedPartUploadCount = uploadDescStartedPartUploadCount.Default.(int)
	// upload.StartedPartUploadCountValidator is a validator for the "startedPartUploadCount" field. It is called by the builders before save.
	upload.StartedPartUploadCountValidator = uploadDescStartedPartUploadCount.Validators[0].(func(int) error)
	// uploadDescFinishedPartUploadCount is the schema descriptor for finishedPartUploadCount field.
	uploadDescFinishedPartUploadCount := uploadFields[8].Descriptor()
	// upload.DefaultFinishedPartUploadCount holds the default value on creation for the finishedPartUploadCount field.
	upload.DefaultFinishedPartUploadCount = uploadDescFinishedPartUploadCount.Default.(int)
	// upload.FinishedPartUploadCountValidator is a validator for the "finishedPartUploadCount" field. It is called by the builders before save.
	upload.FinishedPartUploadCountValidator = uploadDescFinishedPartUploadCount.Validators[0].(func(int) error)
	// uploadDescFolderName is the schema descriptor for folderName field.
	uploadDescFolderName := uploadFields[9].Descriptor()
	// upload.FolderNameValidator is a validator for the "folderName" field. It is called by the builders before save.
	upload.FolderNameValidator = uploadDescFolderName.Validators[0].(func(string) error)
	// uploadDescCommittedPartCount is the schema descriptor for committedPartCount field.
	uploadDescCommittedPartCount := uploadFields[10].Descriptor()
	// upload.CommittedPartCountValidator is a validator for the "committedPartCount" field. It is called by the builders before save.
	upload.CommittedPartCountValidator = uploadDescCommittedPartCount.Validators[0].(func(int) error)
}
