// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagereaderlease"
)

// StorageReaderLeaseQuery is the builder for querying StorageReaderLease entities.
type StorageReaderLeaseQuery struct {
	config
	ctx                 *QueryContext
	order               []storagereaderlease.OrderOption
	inters              []Interceptor
	predicates          []predicate.StorageReaderLease
	withStorageLocation *StorageLocationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StorageReaderLeaseQuery builder.
func (_q *StorageReaderLeaseQuery) Where(ps ...predicate.StorageReaderLease) *StorageReaderLeaseQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *StorageReaderLeaseQuery) Limit(limit int) *StorageReaderLeaseQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *StorageReaderLeaseQuery) Offset(offset int) *StorageReaderLeaseQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *StorageReaderLeaseQuery) Unique(unique bool) *StorageReaderLeaseQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *StorageReaderLeaseQuery) Order(o ...storagereaderlease.OrderOption) *StorageReaderLeaseQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryStorageLocation chains the current query on the "storageLocation" edge.
func (_q *StorageReaderLeaseQuery) QueryStorageLocation() *StorageLocationQuery {
	query := (&StorageLocationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(storagereaderlease.Table, storagereaderlease.FieldID, selector),
			sqlgraph.To(storagelocation.Table, storagelocation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, storagereaderlease.StorageLocationTable, storagereaderlease.StorageLocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StorageReaderLease entity from the query.
// Returns a *NotFoundError when no StorageReaderLease was found.
func (_q *StorageReaderLeaseQuery) First(ctx context.Context) (*StorageReaderLease, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{storagereaderlease.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) FirstX(ctx context.Context) *StorageReaderLease {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StorageReaderLease ID from the query.
// Returns a *NotFoundError when no StorageReaderLease ID was found.
func (_q *StorageReaderLeaseQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{storagereaderlease.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StorageReaderLease entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StorageReaderLease entity is found.
// Returns a *NotFoundError when no StorageReaderLease entities are found.
func (_q *StorageReaderLeaseQuery) Only(ctx context.Context) (*StorageReaderLease, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{storagereaderlease.Label}
	default:
		return nil, &NotSingularError{storagereaderlease.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) OnlyX(ctx context.Context) *StorageReaderLease {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StorageReaderLease ID in the query.
// Returns a *NotSingularError when more than one StorageReaderLease ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *StorageReaderLeaseQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{storagereaderlease.Label}
	default:
		err = &NotSingularError{storagereaderlease.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StorageReaderLeases.
func (_q *StorageReaderLeaseQuery) All(ctx context.Context) ([]*StorageReaderLease, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StorageReaderLease, *StorageReaderLeaseQuery]()
	return withInterceptors[[]*StorageReaderLease](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) AllX(ctx context.Context) []*StorageReaderLease {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StorageReaderLease IDs.
func (_q *StorageReaderLeaseQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(storagereaderlease.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *StorageReaderLeaseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*StorageReaderLeaseQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *StorageReaderLeaseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *StorageReaderLeaseQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StorageReaderLeaseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *StorageReaderLeaseQuery) Clone() *StorageReaderLeaseQuery {
	if _q == nil {
		return nil
	}
	return &StorageReaderLeaseQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]storagereaderlease.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.StorageReaderLease{}, _q.predicates...),
		withStorageLocation: _q.withStorageLocation.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithStorageLocation tells the query-builder to eager-load the nodes that are connected to
// the "storageLocation" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StorageReaderLeaseQuery) WithStorageLocation(opts ...func(*StorageLocationQuery)) *StorageReaderLeaseQuery {
	query := (&StorageLocationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStorageLocation = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StorageLocationId string `json:"storageLocationId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StorageReaderLease.Query().
//		GroupBy(storagereaderlease.FieldStorageLocationId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *StorageReaderLeaseQuery) GroupBy(field string, fields ...string) *StorageReaderLeaseGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StorageReaderLeaseGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = storagereaderlease.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StorageLocationId string `json:"storageLocationId,omitempty"`
//	}
//
//	client.StorageReaderLease.Query().
//		Select(storagereaderlease.FieldStorageLocationId).
//		Scan(ctx, &v)
func (_q *StorageReaderLeaseQuery) Select(fields ...string) *StorageReaderLeaseSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &StorageReaderLeaseSelect{StorageReaderLeaseQuery: _q}
	sbuild.label = storagereaderlease.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StorageReaderLeaseSelect configured with the given aggregations.
func (_q *StorageReaderLeaseQuery) Aggregate(fns ...AggregateFunc) *StorageReaderLeaseSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *StorageReaderLeaseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !storagereaderlease.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *StorageReaderLeaseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StorageReaderLease, error) {
	var (
		nodes       = []*StorageReaderLease{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withStorageLocation != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StorageReaderLease).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StorageReaderLease{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withStorageLocation; query != nil {
		if err := _q.loadStorageLocation(ctx, query, nodes, nil,
			func(n *StorageReaderLease, e *StorageLocation) { n.Edges.StorageLocation = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *StorageReaderLeaseQuery) loadStorageLocation(ctx context.Context, query *StorageLocationQuery, nodes []*StorageReaderLease, init func(*StorageReaderLease), assign func(*StorageReaderLease, *StorageLocation)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*StorageReaderLease)
	for i := range nodes {
		fk := nodes[i].StorageLocationId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(storagelocation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "storageLocationId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *StorageReaderLeaseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *StorageReaderLeaseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(storagereaderlease.Table, storagereaderlease.Columns, sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagereaderlease.FieldID)
		for i := range fields {
			if fields[i] != storagereaderlease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withStorageLocation != nil {
			_spec.Node.AddColumnOnce(storagereaderlease.FieldStorageLocationId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *StorageReaderLeaseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(storagereaderlease.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = storagereaderlease.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StorageReaderLeaseGroupBy is the group-by builder for StorageReaderLease entities.
type StorageReaderLeaseGroupBy struct {
	selector
	build *StorageReaderLeaseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *StorageReaderLeaseGroupBy) Aggregate(fns ...AggregateFunc) *StorageReaderLeaseGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *StorageReaderLeaseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StorageReaderLeaseQuery, *StorageReaderLeaseGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *StorageReaderLeaseGroupBy) sqlScan(ctx context.Context, root *StorageReaderLeaseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StorageReaderLeaseSelect is the builder for selecting fields of StorageReaderLease entities.
type StorageReaderLeaseSelect struct {
	*StorageReaderLeaseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *StorageReaderLeaseSelect) Aggregate(fns ...AggregateFunc) *StorageReaderLeaseSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *StorageReaderLeaseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StorageReaderLeaseQuery, *StorageReaderLeaseSelect](ctx, _s.StorageReaderLeaseQuery, _s, _s.inters, v)
}

func (_s *StorageReaderLeaseSelect) sqlScan(ctx context.Context, root *StorageReaderLeaseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
