// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagereaderlease"
)

// StorageReaderLeaseCreate is the builder for creating a StorageReaderLease entity.
type StorageReaderLeaseCreate struct {
	config
	mutation *StorageReaderLeaseMutation
	hooks    []Hook
}

// SetStorageLocationId sets the "storageLocationId" field.
func (_c *StorageReaderLeaseCreate) SetStorageLocationId(v string) *StorageReaderLeaseCreate {
	_c.mutation.SetStorageLocationId(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *StorageReaderLeaseCreate) SetScope(v storagereaderlease.Scope) *StorageReaderLeaseCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetExpiresAt sets the "expiresAt" field.
func (_c *StorageReaderLeaseCreate) SetExpiresAt(v int64) *StorageReaderLeaseCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *StorageReaderLeaseCreate) SetID(v string) *StorageReaderLeaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetStorageLocationID sets the "storageLocation" edge to the StorageLocation entity by ID.
func (_c *StorageReaderLeaseCreate) SetStorageLocationID(id string) *StorageReaderLeaseCreate {
	_c.mutation.SetStorageLocationID(id)
	return _c
}

// SetStorageLocation sets the "storageLocation" edge to the StorageLocation entity.
func (_c *StorageReaderLeaseCreate) SetStorageLocation(v *StorageLocation) *StorageReaderLeaseCreate {
	return _c.SetStorageLocationID(v.ID)
}

// Mutation returns the StorageReaderLeaseMutation object of the builder.
func (_c *StorageReaderLeaseCreate) Mutation() *StorageReaderLeaseMutation {
	return _c.mutation
}

// Save creates the StorageReaderLease in the database.
func (_c *StorageReaderLeaseCreate) Save(ctx context.Context) (*StorageReaderLease, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StorageReaderLeaseCreate) SaveX(ctx context.Context) *StorageReaderLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageReaderLeaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageReaderLeaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StorageReaderLeaseCreate) check() error {
	if _, ok := _c.mutation.StorageLocationId(); !ok {
		return &ValidationError{Name: "storageLocationId", err: errors.New(`ent: missing required field "StorageReaderLease.storageLocationId"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "StorageReaderLease.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := storagereaderlease.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "StorageReaderLease.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expiresAt", err: errors.New(`ent: missing required field "StorageReaderLease.expiresAt"`)}
	}
	if len(_c.mutation.StorageLocationIDs()) == 0 {
		return &ValidationError{Name: "storageLocation", err: errors.New(`ent: missing required edge "StorageReaderLease.storageLocation"`)}
	}
	return nil
}

func (_c *StorageReaderLeaseCreate) sqlSave(ctx context.Context) (*StorageReaderLease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected StorageReaderLease.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StorageReaderLeaseCreate) createSpec() (*StorageReaderLease, *sqlgraph.CreateSpec) {
	var (
		_node = &StorageReaderLease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storagereaderlease.Table, sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(storagereaderlease.FieldScope, field.TypeEnum, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(storagereaderlease.FieldExpiresAt, field.TypeInt64, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.StorageLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storagereaderlease.StorageLocationTable,
			Columns: []string{storagereaderlease.StorageLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StorageLocationId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StorageReaderLeaseCreateBulk is the builder for creating many StorageReaderLease entities in bulk.
type StorageReaderLeaseCreateBulk struct {
	config
	err      error
	builders []*StorageReaderLeaseCreate
}

// Save creates the StorageReaderLease entities in the database.
func (_c *StorageReaderLeaseCreateBulk) Save(ctx context.Context) ([]*StorageReaderLease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StorageReaderLease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StorageReaderLeaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StorageReaderLeaseCreateBulk) SaveX(ctx context.Context) []*StorageReaderLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageReaderLeaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageReaderLeaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
