// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagereaderlease"
)

// StorageReaderLeaseDelete is the builder for deleting a StorageReaderLease entity.
type StorageReaderLeaseDelete struct {
	config
	hooks    []Hook
	mutation *StorageReaderLeaseMutation
}

// Where appends a list predicates to the StorageReaderLeaseDelete builder.
func (_d *StorageReaderLeaseDelete) Where(ps ...predicate.StorageReaderLease) *StorageReaderLeaseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StorageReaderLeaseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorageReaderLeaseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StorageReaderLeaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storagereaderlease.Table, sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StorageReaderLeaseDeleteOne is the builder for deleting a single StorageReaderLease entity.
type StorageReaderLeaseDeleteOne struct {
	_d *StorageReaderLeaseDelete
}

// Where appends a list predicates to the StorageReaderLeaseDelete builder.
func (_d *StorageReaderLeaseDeleteOne) Where(ps ...predicate.StorageReaderLease) *StorageReaderLeaseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StorageReaderLeaseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storagereaderlease.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorageReaderLeaseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
