// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagereaderlease"
)

// StorageReaderLeaseUpdate is the builder for updating StorageReaderLease entities.
type StorageReaderLeaseUpdate struct {
	config
	hooks    []Hook
	mutation *StorageReaderLeaseMutation
}

// Where appends a list predicates to the StorageReaderLeaseUpdate builder.
func (_u *StorageReaderLeaseUpdate) Where(ps ...predicate.StorageReaderLease) *StorageReaderLeaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStorageLocationId sets the "storageLocationId" field.
func (_u *StorageReaderLeaseUpdate) SetStorageLocationId(v string) *StorageReaderLeaseUpdate {
	_u.mutation.SetStorageLocationId(v)
	return _u
}

// SetNillableStorageLocationId sets the "storageLocationId" field if the given value is not nil.
func (_u *StorageReaderLeaseUpdate) SetNillableStorageLocationId(v *string) *StorageReaderLeaseUpdate {
	if v != nil {
		_u.SetStorageLocationId(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *StorageReaderLeaseUpdate) SetScope(v storagereaderlease.Scope) *StorageReaderLeaseUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *StorageReaderLeaseUpdate) SetNillableScope(v *storagereaderlease.Scope) *StorageReaderLeaseUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *StorageReaderLeaseUpdate) SetExpiresAt(v int64) *StorageReaderLeaseUpdate {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *StorageReaderLeaseUpdate) SetNillableExpiresAt(v *int64) *StorageReaderLeaseUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expiresAt" field.
func (_u *StorageReaderLeaseUpdate) AddExpiresAt(v int64) *StorageReaderLeaseUpdate {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// SetStorageLocationID sets the "storageLocation" edge to the StorageLocation entity by ID.
func (_u *StorageReaderLeaseUpdate) SetStorageLocationID(id string) *StorageReaderLeaseUpdate {
	_u.mutation.SetStorageLocationID(id)
	return _u
}

// SetStorageLocation sets the "storageLocation" edge to the StorageLocation entity.
func (_u *StorageReaderLeaseUpdate) SetStorageLocation(v *StorageLocation) *StorageReaderLeaseUpdate {
	return _u.SetStorageLocationID(v.ID)
}

// Mutation returns the StorageReaderLeaseMutation object of the builder.
func (_u *StorageReaderLeaseUpdate) Mutation() *StorageReaderLeaseMutation {
	return _u.mutation
}

// ClearStorageLocation clears the "storageLocation" edge to the StorageLocation entity.
func (_u *StorageReaderLeaseUpdate) ClearStorageLocation() *StorageReaderLeaseUpdate {
	_u.mutation.ClearStorageLocation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StorageReaderLeaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageReaderLeaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StorageReaderLeaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageReaderLeaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageReaderLeaseUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := storagereaderlease.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "StorageReaderLease.scope": %w`, err)}
		}
	}
	if _u.mutation.StorageLocationCleared() && len(_u.mutation.StorageLocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StorageReaderLease.storageLocation"`)
	}
	return nil
}

func (_u *StorageReaderLeaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagereaderlease.Table, storagereaderlease.Columns, sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(storagereaderlease.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(storagereaderlease.FieldExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(storagereaderlease.FieldExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.StorageLocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storagereaderlease.StorageLocationTable,
			Columns: []string{storagereaderlease.StorageLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StorageLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storagereaderlease.StorageLocationTable,
			Columns: []string{storagereaderlease.StorageLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagereaderlease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StorageReaderLeaseUpdateOne is the builder for updating a single StorageReaderLease entity.
type StorageReaderLeaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StorageReaderLeaseMutation
}

// SetStorageLocationId sets the "storageLocationId" field.
func (_u *StorageReaderLeaseUpdateOne) SetStorageLocationId(v string) *StorageReaderLeaseUpdateOne {
	_u.mutation.SetStorageLocationId(v)
	return _u
}

// SetNillableStorageLocationId sets the "storageLocationId" field if the given value is not nil.
func (_u *StorageReaderLeaseUpdateOne) SetNillableStorageLocationId(v *string) *StorageReaderLeaseUpdateOne {
	if v != nil {
		_u.SetStorageLocationId(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *StorageReaderLeaseUpdateOne) SetScope(v storagereaderlease.Scope) *StorageReaderLeaseUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *StorageReaderLeaseUpdateOne) SetNillableScope(v *storagereaderlease.Scope) *StorageReaderLeaseUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *StorageReaderLeaseUpdateOne) SetExpiresAt(v int64) *StorageReaderLeaseUpdateOne {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *StorageReaderLeaseUpdateOne) SetNillableExpiresAt(v *int64) *StorageReaderLeaseUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expiresAt" field.
func (_u *StorageReaderLeaseUpdateOne) AddExpiresAt(v int64) *StorageReaderLeaseUpdateOne {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// SetStorageLocationID sets the "storageLocation" edge to the StorageLocation entity by ID.
func (_u *StorageReaderLeaseUpdateOne) SetStorageLocationID(id string) *StorageReaderLeaseUpdateOne {
	_u.mutation.SetStorageLocationID(id)
	return _u
}

// SetStorageLocation sets the "storageLocation" edge to the StorageLocation entity.
func (_u *StorageReaderLeaseUpdateOne) SetStorageLocation(v *StorageLocation) *StorageReaderLeaseUpdateOne {
	return _u.SetStorageLocationID(v.ID)
}

// Mutation returns the StorageReaderLeaseMutation object of the builder.
func (_u *StorageReaderLeaseUpdateOne) Mutation() *StorageReaderLeaseMutation {
	return _u.mutation
}

// ClearStorageLocation clears the "storageLocation" edge to the StorageLocation entity.
func (_u *StorageReaderLeaseUpdateOne) ClearStorageLocation() *StorageReaderLeaseUpdateOne {
	_u.mutation.ClearStorageLocation()
	return _u
}

// Where appends a list predicates to the StorageReaderLeaseUpdate builder.
func (_u *StorageReaderLeaseUpdateOne) Where(ps ...predicate.StorageReaderLease) *StorageReaderLeaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StorageReaderLeaseUpdateOne) Select(field string, fields ...string) *StorageReaderLeaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StorageReaderLease entity.
func (_u *StorageReaderLeaseUpdateOne) Save(ctx context.Context) (*StorageReaderLease, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageReaderLeaseUpdateOne) SaveX(ctx context.Context) *StorageReaderLease {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StorageReaderLeaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageReaderLeaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageReaderLeaseUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := storagereaderlease.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "StorageReaderLease.scope": %w`, err)}
		}
	}
	if _u.mutation.StorageLocationCleared() && len(_u.mutation.StorageLocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StorageReaderLease.storageLocation"`)
	}
	return nil
}

func (_u *StorageReaderLeaseUpdateOne) sqlSave(ctx context.Context) (_node *StorageReaderLease, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagereaderlease.Table, storagereaderlease.Columns, sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StorageReaderLease.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagereaderlease.FieldID)
		for _, f := range fields {
			if !storagereaderlease.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storagereaderlease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(storagereaderlease.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(storagereaderlease.FieldExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(storagereaderlease.FieldExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.StorageLocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storagereaderlease.StorageLocationTable,
			Columns: []string{storagereaderlease.StorageLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StorageLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storagereaderlease.StorageLocationTable,
			Columns: []string{storagereaderlease.StorageLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StorageReaderLease{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagereaderlease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
