// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagedeletion"
)

// StorageDeletionUpdate is the builder for updating StorageDeletion entities.
type StorageDeletionUpdate struct {
	config
	hooks    []Hook
	mutation *StorageDeletionMutation
}

// Where appends a list predicates to the StorageDeletionUpdate builder.
func (_u *StorageDeletionUpdate) Where(ps ...predicate.StorageDeletion) *StorageDeletionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFolderName sets the "folderName" field.
func (_u *StorageDeletionUpdate) SetFolderName(v string) *StorageDeletionUpdate {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folderName" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableFolderName(v *string) *StorageDeletionUpdate {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *StorageDeletionUpdate) SetCreatedAt(v int64) *StorageDeletionUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableCreatedAt(v *int64) *StorageDeletionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "createdAt" field.
func (_u *StorageDeletionUpdate) AddCreatedAt(v int64) *StorageDeletionUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetAttemptCount sets the "attemptCount" field.
func (_u *StorageDeletionUpdate) SetAttemptCount(v int) *StorageDeletionUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attemptCount" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableAttemptCount(v *int) *StorageDeletionUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attemptCount" field.
func (_u *StorageDeletionUpdate) AddAttemptCount(v int) *StorageDeletionUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLastAttemptedAt sets the "lastAttemptedAt" field.
func (_u *StorageDeletionUpdate) SetLastAttemptedAt(v int64) *StorageDeletionUpdate {
	_u.mutation.ResetLastAttemptedAt()
	_u.mutation.SetLastAttemptedAt(v)
	return _u
}

// SetNillableLastAttemptedAt sets the "lastAttemptedAt" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableLastAttemptedAt(v *int64) *StorageDeletionUpdate {
	if v != nil {
		_u.SetLastAttemptedAt(*v)
	}
	return _u
}

// AddLastAttemptedAt adds value to the "lastAttemptedAt" field.
func (_u *StorageDeletionUpdate) AddLastAttemptedAt(v int64) *StorageDeletionUpdate {
	_u.mutation.AddLastAttemptedAt(v)
	return _u
}

// ClearLastAttemptedAt clears the value of the "lastAttemptedAt" field.
func (_u *StorageDeletionUpdate) ClearLastAttemptedAt() *StorageDeletionUpdate {
	_u.mutation.ClearLastAttemptedAt()
	return _u
}

// SetLastError sets the "lastError" field.
func (_u *StorageDeletionUpdate) SetLastError(v string) *StorageDeletionUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "lastError" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableLastError(v *string) *StorageDeletionUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "lastError" field.
func (_u *StorageDeletionUpdate) ClearLastError() *StorageDeletionUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the StorageDeletionMutation object of the builder.
func (_u *StorageDeletionUpdate) Mutation() *StorageDeletionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StorageDeletionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageDeletionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StorageDeletionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageDeletionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageDeletionUpdate) check() error {
	if v, ok := _u.mutation.FolderName(); ok {
		if err := storagedeletion.FolderNameValidator(v); err != nil {
			return &ValidationError{Name: "folderName", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.folderName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := storagedeletion.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attemptCount", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.attemptCount": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageDeletionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagedeletion.Table, storagedeletion.Columns, sqlgraph.NewFieldSpec(storagedeletion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(storagedeletion.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(storagedeletion.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(storagedeletion.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastAttemptedAt(); ok {
		_spec.SetField(storagedeletion.FieldLastAttemptedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastAttemptedAt(); ok {
		_spec.AddField(storagedeletion.FieldLastAttemptedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastAttemptedAtCleared() {
		_spec.ClearField(storagedeletion.FieldLastAttemptedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(storagedeletion.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(storagedeletion.FieldLastError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagedeletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StorageDeletionUpdateOne is the builder for updating a single StorageDeletion entity.
type StorageDeletionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StorageDeletionMutation
}

// SetFolderName sets the "folderName" field.
func (_u *StorageDeletionUpdateOne) SetFolderName(v string) *StorageDeletionUpdateOne {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folderName" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableFolderName(v *string) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *StorageDeletionUpdateOne) SetCreatedAt(v int64) *StorageDeletionUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableCreatedAt(v *int64) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "createdAt" field.
func (_u *StorageDeletionUpdateOne) AddCreatedAt(v int64) *StorageDeletionUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetAttemptCount sets the "attemptCount" field.
func (_u *StorageDeletionUpdateOne) SetAttemptCount(v int) *StorageDeletionUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attemptCount" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableAttemptCount(v *int) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attemptCount" field.
func (_u *StorageDeletionUpdateOne) AddAttemptCount(v int) *StorageDeletionUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLastAttemptedAt sets the "lastAttemptedAt" field.
func (_u *StorageDeletionUpdateOne) SetLastAttemptedAt(v int64) *StorageDeletionUpdateOne {
	_u.mutation.ResetLastAttemptedAt()
	_u.mutation.SetLastAttemptedAt(v)
	return _u
}

// SetNillableLastAttemptedAt sets the "lastAttemptedAt" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableLastAttemptedAt(v *int64) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetLastAttemptedAt(*v)
	}
	return _u
}

// AddLastAttemptedAt adds value to the "lastAttemptedAt" field.
func (_u *StorageDeletionUpdateOne) AddLastAttemptedAt(v int64) *StorageDeletionUpdateOne {
	_u.mutation.AddLastAttemptedAt(v)
	return _u
}

// ClearLastAttemptedAt clears the value of the "lastAttemptedAt" field.
func (_u *StorageDeletionUpdateOne) ClearLastAttemptedAt() *StorageDeletionUpdateOne {
	_u.mutation.ClearLastAttemptedAt()
	return _u
}

// SetLastError sets the "lastError" field.
func (_u *StorageDeletionUpdateOne) SetLastError(v string) *StorageDeletionUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "lastError" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableLastError(v *string) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "lastError" field.
func (_u *StorageDeletionUpdateOne) ClearLastError() *StorageDeletionUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the StorageDeletionMutation object of the builder.
func (_u *StorageDeletionUpdateOne) Mutation() *StorageDeletionMutation {
	return _u.mutation
}

// Where appends a list predicates to the StorageDeletionUpdate builder.
func (_u *StorageDeletionUpdateOne) Where(ps ...predicate.StorageDeletion) *StorageDeletionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StorageDeletionUpdateOne) Select(field string, fields ...string) *StorageDeletionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StorageDeletion entity.
func (_u *StorageDeletionUpdateOne) Save(ctx context.Context) (*StorageDeletion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageDeletionUpdateOne) SaveX(ctx context.Context) *StorageDeletion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StorageDeletionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageDeletionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageDeletionUpdateOne) check() error {
	if v, ok := _u.mutation.FolderName(); ok {
		if err := storagedeletion.FolderNameValidator(v); err != nil {
			return &ValidationError{Name: "folderName", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.folderName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := storagedeletion.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attemptCount", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.attemptCount": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageDeletionUpdateOne) sqlSave(ctx context.Context) (_node *StorageDeletion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagedeletion.Table, storagedeletion.Columns, sqlgraph.NewFieldSpec(storagedeletion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StorageDeletion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagedeletion.FieldID)
		for _, f := range fields {
			if !storagedeletion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storagedeletion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(storagedeletion.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(storagedeletion.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(storagedeletion.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastAttemptedAt(); ok {
		_spec.SetField(storagedeletion.FieldLastAttemptedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastAttemptedAt(); ok {
		_spec.AddField(storagedeletion.FieldLastAttemptedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastAttemptedAtCleared() {
		_spec.ClearField(storagedeletion.FieldLastAttemptedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(storagedeletion.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(storagedeletion.FieldLastError, field.TypeString)
	}
	_node = &StorageDeletion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagedeletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
