// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/cacheentry"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagereaderlease"
)

// StorageLocationUpdate is the builder for updating StorageLocation entities.
type StorageLocationUpdate struct {
	config
	hooks    []Hook
	mutation *StorageLocationMutation
}

// Where appends a list predicates to the StorageLocationUpdate builder.
func (_u *StorageLocationUpdate) Where(ps ...predicate.StorageLocation) *StorageLocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFolderName sets the "folderName" field.
func (_u *StorageLocationUpdate) SetFolderName(v string) *StorageLocationUpdate {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folderName" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableFolderName(v *string) *StorageLocationUpdate {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetPartCount sets the "partCount" field.
func (_u *StorageLocationUpdate) SetPartCount(v int) *StorageLocationUpdate {
	_u.mutation.ResetPartCount()
	_u.mutation.SetPartCount(v)
	return _u
}

// SetNillablePartCount sets the "partCount" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillablePartCount(v *int) *StorageLocationUpdate {
	if v != nil {
		_u.SetPartCount(*v)
	}
	return _u
}

// AddPartCount adds value to the "partCount" field.
func (_u *StorageLocationUpdate) AddPartCount(v int) *StorageLocationUpdate {
	_u.mutation.AddPartCount(v)
	return _u
}

// SetSizeBytes sets the "sizeBytes" field.
func (_u *StorageLocationUpdate) SetSizeBytes(v int64) *StorageLocationUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "sizeBytes" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableSizeBytes(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "sizeBytes" field.
func (_u *StorageLocationUpdate) AddSizeBytes(v int64) *StorageLocationUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// ClearSizeBytes clears the value of the "sizeBytes" field.
func (_u *StorageLocationUpdate) ClearSizeBytes() *StorageLocationUpdate {
	_u.mutation.ClearSizeBytes()
	return _u
}

// SetLeaseVersion sets the "leaseVersion" field.
func (_u *StorageLocationUpdate) SetLeaseVersion(v int64) *StorageLocationUpdate {
	_u.mutation.ResetLeaseVersion()
	_u.mutation.SetLeaseVersion(v)
	return _u
}

// SetNillableLeaseVersion sets the "leaseVersion" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableLeaseVersion(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetLeaseVersion(*v)
	}
	return _u
}

// AddLeaseVersion adds value to the "leaseVersion" field.
func (_u *StorageLocationUpdate) AddLeaseVersion(v int64) *StorageLocationUpdate {
	_u.mutation.AddLeaseVersion(v)
	return _u
}

// SetDeletionRequestedAt sets the "deletionRequestedAt" field.
func (_u *StorageLocationUpdate) SetDeletionRequestedAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetDeletionRequestedAt()
	_u.mutation.SetDeletionRequestedAt(v)
	return _u
}

// SetNillableDeletionRequestedAt sets the "deletionRequestedAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableDeletionRequestedAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetDeletionRequestedAt(*v)
	}
	return _u
}

// AddDeletionRequestedAt adds value to the "deletionRequestedAt" field.
func (_u *StorageLocationUpdate) AddDeletionRequestedAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddDeletionRequestedAt(v)
	return _u
}

// ClearDeletionRequestedAt clears the value of the "deletionRequestedAt" field.
func (_u *StorageLocationUpdate) ClearDeletionRequestedAt() *StorageLocationUpdate {
	_u.mutation.ClearDeletionRequestedAt()
	return _u
}

// SetMergeStartedAt sets the "mergeStartedAt" field.
func (_u *StorageLocationUpdate) SetMergeStartedAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetMergeStartedAt()
	_u.mutation.SetMergeStartedAt(v)
	return _u
}

// SetNillableMergeStartedAt sets the "mergeStartedAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableMergeStartedAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetMergeStartedAt(*v)
	}
	return _u
}

// AddMergeStartedAt adds value to the "mergeStartedAt" field.
func (_u *StorageLocationUpdate) AddMergeStartedAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddMergeStartedAt(v)
	return _u
}

// ClearMergeStartedAt clears the value of the "mergeStartedAt" field.
func (_u *StorageLocationUpdate) ClearMergeStartedAt() *StorageLocationUpdate {
	_u.mutation.ClearMergeStartedAt()
	return _u
}

// SetMergeLeaseToken sets the "mergeLeaseToken" field.
func (_u *StorageLocationUpdate) SetMergeLeaseToken(v string) *StorageLocationUpdate {
	_u.mutation.SetMergeLeaseToken(v)
	return _u
}

// SetNillableMergeLeaseToken sets the "mergeLeaseToken" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableMergeLeaseToken(v *string) *StorageLocationUpdate {
	if v != nil {
		_u.SetMergeLeaseToken(*v)
	}
	return _u
}

// ClearMergeLeaseToken clears the value of the "mergeLeaseToken" field.
func (_u *StorageLocationUpdate) ClearMergeLeaseToken() *StorageLocationUpdate {
	_u.mutation.ClearMergeLeaseToken()
	return _u
}

// SetMergeLeaseExpiresAt sets the "mergeLeaseExpiresAt" field.
func (_u *StorageLocationUpdate) SetMergeLeaseExpiresAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetMergeLeaseExpiresAt()
	_u.mutation.SetMergeLeaseExpiresAt(v)
	return _u
}

// SetNillableMergeLeaseExpiresAt sets the "mergeLeaseExpiresAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableMergeLeaseExpiresAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetMergeLeaseExpiresAt(*v)
	}
	return _u
}

// AddMergeLeaseExpiresAt adds value to the "mergeLeaseExpiresAt" field.
func (_u *StorageLocationUpdate) AddMergeLeaseExpiresAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddMergeLeaseExpiresAt(v)
	return _u
}

// ClearMergeLeaseExpiresAt clears the value of the "mergeLeaseExpiresAt" field.
func (_u *StorageLocationUpdate) ClearMergeLeaseExpiresAt() *StorageLocationUpdate {
	_u.mutation.ClearMergeLeaseExpiresAt()
	return _u
}

// SetMergedAt sets the "mergedAt" field.
func (_u *StorageLocationUpdate) SetMergedAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetMergedAt()
	_u.mutation.SetMergedAt(v)
	return _u
}

// SetNillableMergedAt sets the "mergedAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableMergedAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetMergedAt(*v)
	}
	return _u
}

// AddMergedAt adds value to the "mergedAt" field.
func (_u *StorageLocationUpdate) AddMergedAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddMergedAt(v)
	return _u
}

// ClearMergedAt clears the value of the "mergedAt" field.
func (_u *StorageLocationUpdate) ClearMergedAt() *StorageLocationUpdate {
	_u.mutation.ClearMergedAt()
	return _u
}

// SetMaterializationUnsupportedAt sets the "materializationUnsupportedAt" field.
func (_u *StorageLocationUpdate) SetMaterializationUnsupportedAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetMaterializationUnsupportedAt()
	_u.mutation.SetMaterializationUnsupportedAt(v)
	return _u
}

// SetNillableMaterializationUnsupportedAt sets the "materializationUnsupportedAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableMaterializationUnsupportedAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetMaterializationUnsupportedAt(*v)
	}
	return _u
}

// AddMaterializationUnsupportedAt adds value to the "materializationUnsupportedAt" field.
func (_u *StorageLocationUpdate) AddMaterializationUnsupportedAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddMaterializationUnsupportedAt(v)
	return _u
}

// ClearMaterializationUnsupportedAt clears the value of the "materializationUnsupportedAt" field.
func (_u *StorageLocationUpdate) ClearMaterializationUnsupportedAt() *StorageLocationUpdate {
	_u.mutation.ClearMaterializationUnsupportedAt()
	return _u
}

// SetPartsDeletedAt sets the "partsDeletedAt" field.
func (_u *StorageLocationUpdate) SetPartsDeletedAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetPartsDeletedAt()
	_u.mutation.SetPartsDeletedAt(v)
	return _u
}

// SetNillablePartsDeletedAt sets the "partsDeletedAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillablePartsDeletedAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetPartsDeletedAt(*v)
	}
	return _u
}

// AddPartsDeletedAt adds value to the "partsDeletedAt" field.
func (_u *StorageLocationUpdate) AddPartsDeletedAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddPartsDeletedAt(v)
	return _u
}

// ClearPartsDeletedAt clears the value of the "partsDeletedAt" field.
func (_u *StorageLocationUpdate) ClearPartsDeletedAt() *StorageLocationUpdate {
	_u.mutation.ClearPartsDeletedAt()
	return _u
}

// SetLastDownloadedAt sets the "lastDownloadedAt" field.
func (_u *StorageLocationUpdate) SetLastDownloadedAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetLastDownloadedAt()
	_u.mutation.SetLastDownloadedAt(v)
	return _u
}

// SetNillableLastDownloadedAt sets the "lastDownloadedAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableLastDownloadedAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetLastDownloadedAt(*v)
	}
	return _u
}

// AddLastDownloadedAt adds value to the "lastDownloadedAt" field.
func (_u *StorageLocationUpdate) AddLastDownloadedAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddLastDownloadedAt(v)
	return _u
}

// ClearLastDownloadedAt clears the value of the "lastDownloadedAt" field.
func (_u *StorageLocationUpdate) ClearLastDownloadedAt() *StorageLocationUpdate {
	_u.mutation.ClearLastDownloadedAt()
	return _u
}

// SetRecencyAt sets the "recencyAt" field.
func (_u *StorageLocationUpdate) SetRecencyAt(v int64) *StorageLocationUpdate {
	_u.mutation.ResetRecencyAt()
	_u.mutation.SetRecencyAt(v)
	return _u
}

// SetNillableRecencyAt sets the "recencyAt" field if the given value is not nil.
func (_u *StorageLocationUpdate) SetNillableRecencyAt(v *int64) *StorageLocationUpdate {
	if v != nil {
		_u.SetRecencyAt(*v)
	}
	return _u
}

// AddRecencyAt adds value to the "recencyAt" field.
func (_u *StorageLocationUpdate) AddRecencyAt(v int64) *StorageLocationUpdate {
	_u.mutation.AddRecencyAt(v)
	return _u
}

// AddCacheEntryIDs adds the "cacheEntries" edge to the CacheEntry entity by IDs.
func (_u *StorageLocationUpdate) AddCacheEntryIDs(ids ...string) *StorageLocationUpdate {
	_u.mutation.AddCacheEntryIDs(ids...)
	return _u
}

// AddCacheEntries adds the "cacheEntries" edges to the CacheEntry entity.
func (_u *StorageLocationUpdate) AddCacheEntries(v ...*CacheEntry) *StorageLocationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCacheEntryIDs(ids...)
}

// AddReaderLeaseIDs adds the "readerLeases" edge to the StorageReaderLease entity by IDs.
func (_u *StorageLocationUpdate) AddReaderLeaseIDs(ids ...string) *StorageLocationUpdate {
	_u.mutation.AddReaderLeaseIDs(ids...)
	return _u
}

// AddReaderLeases adds the "readerLeases" edges to the StorageReaderLease entity.
func (_u *StorageLocationUpdate) AddReaderLeases(v ...*StorageReaderLease) *StorageLocationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReaderLeaseIDs(ids...)
}

// Mutation returns the StorageLocationMutation object of the builder.
func (_u *StorageLocationUpdate) Mutation() *StorageLocationMutation {
	return _u.mutation
}

// ClearCacheEntries clears all "cacheEntries" edges to the CacheEntry entity.
func (_u *StorageLocationUpdate) ClearCacheEntries() *StorageLocationUpdate {
	_u.mutation.ClearCacheEntries()
	return _u
}

// RemoveCacheEntryIDs removes the "cacheEntries" edge to CacheEntry entities by IDs.
func (_u *StorageLocationUpdate) RemoveCacheEntryIDs(ids ...string) *StorageLocationUpdate {
	_u.mutation.RemoveCacheEntryIDs(ids...)
	return _u
}

// RemoveCacheEntries removes "cacheEntries" edges to CacheEntry entities.
func (_u *StorageLocationUpdate) RemoveCacheEntries(v ...*CacheEntry) *StorageLocationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCacheEntryIDs(ids...)
}

// ClearReaderLeases clears all "readerLeases" edges to the StorageReaderLease entity.
func (_u *StorageLocationUpdate) ClearReaderLeases() *StorageLocationUpdate {
	_u.mutation.ClearReaderLeases()
	return _u
}

// RemoveReaderLeaseIDs removes the "readerLeases" edge to StorageReaderLease entities by IDs.
func (_u *StorageLocationUpdate) RemoveReaderLeaseIDs(ids ...string) *StorageLocationUpdate {
	_u.mutation.RemoveReaderLeaseIDs(ids...)
	return _u
}

// RemoveReaderLeases removes "readerLeases" edges to StorageReaderLease entities.
func (_u *StorageLocationUpdate) RemoveReaderLeases(v ...*StorageReaderLease) *StorageLocationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReaderLeaseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StorageLocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageLocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StorageLocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageLocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageLocationUpdate) check() error {
	if v, ok := _u.mutation.FolderName(); ok {
		if err := storagelocation.FolderNameValidator(v); err != nil {
			return &ValidationError{Name: "folderName", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.folderName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PartCount(); ok {
		if err := storagelocation.PartCountValidator(v); err != nil {
			return &ValidationError{Name: "partCount", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.partCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := storagelocation.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "sizeBytes", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.sizeBytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseVersion(); ok {
		if err := storagelocation.LeaseVersionValidator(v); err != nil {
			return &ValidationError{Name: "leaseVersion", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.leaseVersion": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecencyAt(); ok {
		if err := storagelocation.RecencyAtValidator(v); err != nil {
			return &ValidationError{Name: "recencyAt", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.recencyAt": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageLocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagelocation.Table, storagelocation.Columns, sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(storagelocation.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PartCount(); ok {
		_spec.SetField(storagelocation.FieldPartCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPartCount(); ok {
		_spec.AddField(storagelocation.FieldPartCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(storagelocation.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(storagelocation.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.SizeBytesCleared() {
		_spec.ClearField(storagelocation.FieldSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.LeaseVersion(); ok {
		_spec.SetField(storagelocation.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseVersion(); ok {
		_spec.AddField(storagelocation.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletionRequestedAt(); ok {
		_spec.SetField(storagelocation.FieldDeletionRequestedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletionRequestedAt(); ok {
		_spec.AddField(storagelocation.FieldDeletionRequestedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletionRequestedAtCleared() {
		_spec.ClearField(storagelocation.FieldDeletionRequestedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MergeStartedAt(); ok {
		_spec.SetField(storagelocation.FieldMergeStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMergeStartedAt(); ok {
		_spec.AddField(storagelocation.FieldMergeStartedAt, field.TypeInt64, value)
	}
	if _u.mutation.MergeStartedAtCleared() {
		_spec.ClearField(storagelocation.FieldMergeStartedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MergeLeaseToken(); ok {
		_spec.SetField(storagelocation.FieldMergeLeaseToken, field.TypeString, value)
	}
	if _u.mutation.MergeLeaseTokenCleared() {
		_spec.ClearField(storagelocation.FieldMergeLeaseToken, field.TypeString)
	}
	if value, ok := _u.mutation.MergeLeaseExpiresAt(); ok {
		_spec.SetField(storagelocation.FieldMergeLeaseExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMergeLeaseExpiresAt(); ok {
		_spec.AddField(storagelocation.FieldMergeLeaseExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.MergeLeaseExpiresAtCleared() {
		_spec.ClearField(storagelocation.FieldMergeLeaseExpiresAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MergedAt(); ok {
		_spec.SetField(storagelocation.FieldMergedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMergedAt(); ok {
		_spec.AddField(storagelocation.FieldMergedAt, field.TypeInt64, value)
	}
	if _u.mutation.MergedAtCleared() {
		_spec.ClearField(storagelocation.FieldMergedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaterializationUnsupportedAt(); ok {
		_spec.SetField(storagelocation.FieldMaterializationUnsupportedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaterializationUnsupportedAt(); ok {
		_spec.AddField(storagelocation.FieldMaterializationUnsupportedAt, field.TypeInt64, value)
	}
	if _u.mutation.MaterializationUnsupportedAtCleared() {
		_spec.ClearField(storagelocation.FieldMaterializationUnsupportedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.PartsDeletedAt(); ok {
		_spec.SetField(storagelocation.FieldPartsDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPartsDeletedAt(); ok {
		_spec.AddField(storagelocation.FieldPartsDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.PartsDeletedAtCleared() {
		_spec.ClearField(storagelocation.FieldPartsDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastDownloadedAt(); ok {
		_spec.SetField(storagelocation.FieldLastDownloadedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDownloadedAt(); ok {
		_spec.AddField(storagelocation.FieldLastDownloadedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastDownloadedAtCleared() {
		_spec.ClearField(storagelocation.FieldLastDownloadedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.RecencyAt(); ok {
		_spec.SetField(storagelocation.FieldRecencyAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecencyAt(); ok {
		_spec.AddField(storagelocation.FieldRecencyAt, field.TypeInt64, value)
	}
	if _u.mutation.CacheEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.CacheEntriesTable,
			Columns: []string{storagelocation.CacheEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCacheEntriesIDs(); len(nodes) > 0 && !_u.mutation.CacheEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.CacheEntriesTable,
			Columns: []string{storagelocation.CacheEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CacheEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.CacheEntriesTable,
			Columns: []string{storagelocation.CacheEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReaderLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.ReaderLeasesTable,
			Columns: []string{storagelocation.ReaderLeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReaderLeasesIDs(); len(nodes) > 0 && !_u.mutation.ReaderLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.ReaderLeasesTable,
			Columns: []string{storagelocation.ReaderLeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReaderLeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.ReaderLeasesTable,
			Columns: []string{storagelocation.ReaderLeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagelocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StorageLocationUpdateOne is the builder for updating a single StorageLocation entity.
type StorageLocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StorageLocationMutation
}

// SetFolderName sets the "folderName" field.
func (_u *StorageLocationUpdateOne) SetFolderName(v string) *StorageLocationUpdateOne {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folderName" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableFolderName(v *string) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetPartCount sets the "partCount" field.
func (_u *StorageLocationUpdateOne) SetPartCount(v int) *StorageLocationUpdateOne {
	_u.mutation.ResetPartCount()
	_u.mutation.SetPartCount(v)
	return _u
}

// SetNillablePartCount sets the "partCount" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillablePartCount(v *int) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetPartCount(*v)
	}
	return _u
}

// AddPartCount adds value to the "partCount" field.
func (_u *StorageLocationUpdateOne) AddPartCount(v int) *StorageLocationUpdateOne {
	_u.mutation.AddPartCount(v)
	return _u
}

// SetSizeBytes sets the "sizeBytes" field.
func (_u *StorageLocationUpdateOne) SetSizeBytes(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "sizeBytes" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableSizeBytes(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "sizeBytes" field.
func (_u *StorageLocationUpdateOne) AddSizeBytes(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// ClearSizeBytes clears the value of the "sizeBytes" field.
func (_u *StorageLocationUpdateOne) ClearSizeBytes() *StorageLocationUpdateOne {
	_u.mutation.ClearSizeBytes()
	return _u
}

// SetLeaseVersion sets the "leaseVersion" field.
func (_u *StorageLocationUpdateOne) SetLeaseVersion(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetLeaseVersion()
	_u.mutation.SetLeaseVersion(v)
	return _u
}

// SetNillableLeaseVersion sets the "leaseVersion" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableLeaseVersion(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetLeaseVersion(*v)
	}
	return _u
}

// AddLeaseVersion adds value to the "leaseVersion" field.
func (_u *StorageLocationUpdateOne) AddLeaseVersion(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddLeaseVersion(v)
	return _u
}

// SetDeletionRequestedAt sets the "deletionRequestedAt" field.
func (_u *StorageLocationUpdateOne) SetDeletionRequestedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetDeletionRequestedAt()
	_u.mutation.SetDeletionRequestedAt(v)
	return _u
}

// SetNillableDeletionRequestedAt sets the "deletionRequestedAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableDeletionRequestedAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetDeletionRequestedAt(*v)
	}
	return _u
}

// AddDeletionRequestedAt adds value to the "deletionRequestedAt" field.
func (_u *StorageLocationUpdateOne) AddDeletionRequestedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddDeletionRequestedAt(v)
	return _u
}

// ClearDeletionRequestedAt clears the value of the "deletionRequestedAt" field.
func (_u *StorageLocationUpdateOne) ClearDeletionRequestedAt() *StorageLocationUpdateOne {
	_u.mutation.ClearDeletionRequestedAt()
	return _u
}

// SetMergeStartedAt sets the "mergeStartedAt" field.
func (_u *StorageLocationUpdateOne) SetMergeStartedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetMergeStartedAt()
	_u.mutation.SetMergeStartedAt(v)
	return _u
}

// SetNillableMergeStartedAt sets the "mergeStartedAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableMergeStartedAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetMergeStartedAt(*v)
	}
	return _u
}

// AddMergeStartedAt adds value to the "mergeStartedAt" field.
func (_u *StorageLocationUpdateOne) AddMergeStartedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddMergeStartedAt(v)
	return _u
}

// ClearMergeStartedAt clears the value of the "mergeStartedAt" field.
func (_u *StorageLocationUpdateOne) ClearMergeStartedAt() *StorageLocationUpdateOne {
	_u.mutation.ClearMergeStartedAt()
	return _u
}

// SetMergeLeaseToken sets the "mergeLeaseToken" field.
func (_u *StorageLocationUpdateOne) SetMergeLeaseToken(v string) *StorageLocationUpdateOne {
	_u.mutation.SetMergeLeaseToken(v)
	return _u
}

// SetNillableMergeLeaseToken sets the "mergeLeaseToken" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableMergeLeaseToken(v *string) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetMergeLeaseToken(*v)
	}
	return _u
}

// ClearMergeLeaseToken clears the value of the "mergeLeaseToken" field.
func (_u *StorageLocationUpdateOne) ClearMergeLeaseToken() *StorageLocationUpdateOne {
	_u.mutation.ClearMergeLeaseToken()
	return _u
}

// SetMergeLeaseExpiresAt sets the "mergeLeaseExpiresAt" field.
func (_u *StorageLocationUpdateOne) SetMergeLeaseExpiresAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetMergeLeaseExpiresAt()
	_u.mutation.SetMergeLeaseExpiresAt(v)
	return _u
}

// SetNillableMergeLeaseExpiresAt sets the "mergeLeaseExpiresAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableMergeLeaseExpiresAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetMergeLeaseExpiresAt(*v)
	}
	return _u
}

// AddMergeLeaseExpiresAt adds value to the "mergeLeaseExpiresAt" field.
func (_u *StorageLocationUpdateOne) AddMergeLeaseExpiresAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddMergeLeaseExpiresAt(v)
	return _u
}

// ClearMergeLeaseExpiresAt clears the value of the "mergeLeaseExpiresAt" field.
func (_u *StorageLocationUpdateOne) ClearMergeLeaseExpiresAt() *StorageLocationUpdateOne {
	_u.mutation.ClearMergeLeaseExpiresAt()
	return _u
}

// SetMergedAt sets the "mergedAt" field.
func (_u *StorageLocationUpdateOne) SetMergedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetMergedAt()
	_u.mutation.SetMergedAt(v)
	return _u
}

// SetNillableMergedAt sets the "mergedAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableMergedAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetMergedAt(*v)
	}
	return _u
}

// AddMergedAt adds value to the "mergedAt" field.
func (_u *StorageLocationUpdateOne) AddMergedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddMergedAt(v)
	return _u
}

// ClearMergedAt clears the value of the "mergedAt" field.
func (_u *StorageLocationUpdateOne) ClearMergedAt() *StorageLocationUpdateOne {
	_u.mutation.ClearMergedAt()
	return _u
}

// SetMaterializationUnsupportedAt sets the "materializationUnsupportedAt" field.
func (_u *StorageLocationUpdateOne) SetMaterializationUnsupportedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetMaterializationUnsupportedAt()
	_u.mutation.SetMaterializationUnsupportedAt(v)
	return _u
}

// SetNillableMaterializationUnsupportedAt sets the "materializationUnsupportedAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableMaterializationUnsupportedAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetMaterializationUnsupportedAt(*v)
	}
	return _u
}

// AddMaterializationUnsupportedAt adds value to the "materializationUnsupportedAt" field.
func (_u *StorageLocationUpdateOne) AddMaterializationUnsupportedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddMaterializationUnsupportedAt(v)
	return _u
}

// ClearMaterializationUnsupportedAt clears the value of the "materializationUnsupportedAt" field.
func (_u *StorageLocationUpdateOne) ClearMaterializationUnsupportedAt() *StorageLocationUpdateOne {
	_u.mutation.ClearMaterializationUnsupportedAt()
	return _u
}

// SetPartsDeletedAt sets the "partsDeletedAt" field.
func (_u *StorageLocationUpdateOne) SetPartsDeletedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetPartsDeletedAt()
	_u.mutation.SetPartsDeletedAt(v)
	return _u
}

// SetNillablePartsDeletedAt sets the "partsDeletedAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillablePartsDeletedAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetPartsDeletedAt(*v)
	}
	return _u
}

// AddPartsDeletedAt adds value to the "partsDeletedAt" field.
func (_u *StorageLocationUpdateOne) AddPartsDeletedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddPartsDeletedAt(v)
	return _u
}

// ClearPartsDeletedAt clears the value of the "partsDeletedAt" field.
func (_u *StorageLocationUpdateOne) ClearPartsDeletedAt() *StorageLocationUpdateOne {
	_u.mutation.ClearPartsDeletedAt()
	return _u
}

// SetLastDownloadedAt sets the "lastDownloadedAt" field.
func (_u *StorageLocationUpdateOne) SetLastDownloadedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetLastDownloadedAt()
	_u.mutation.SetLastDownloadedAt(v)
	return _u
}

// SetNillableLastDownloadedAt sets the "lastDownloadedAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableLastDownloadedAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetLastDownloadedAt(*v)
	}
	return _u
}

// AddLastDownloadedAt adds value to the "lastDownloadedAt" field.
func (_u *StorageLocationUpdateOne) AddLastDownloadedAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddLastDownloadedAt(v)
	return _u
}

// ClearLastDownloadedAt clears the value of the "lastDownloadedAt" field.
func (_u *StorageLocationUpdateOne) ClearLastDownloadedAt() *StorageLocationUpdateOne {
	_u.mutation.ClearLastDownloadedAt()
	return _u
}

// SetRecencyAt sets the "recencyAt" field.
func (_u *StorageLocationUpdateOne) SetRecencyAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.ResetRecencyAt()
	_u.mutation.SetRecencyAt(v)
	return _u
}

// SetNillableRecencyAt sets the "recencyAt" field if the given value is not nil.
func (_u *StorageLocationUpdateOne) SetNillableRecencyAt(v *int64) *StorageLocationUpdateOne {
	if v != nil {
		_u.SetRecencyAt(*v)
	}
	return _u
}

// AddRecencyAt adds value to the "recencyAt" field.
func (_u *StorageLocationUpdateOne) AddRecencyAt(v int64) *StorageLocationUpdateOne {
	_u.mutation.AddRecencyAt(v)
	return _u
}

// AddCacheEntryIDs adds the "cacheEntries" edge to the CacheEntry entity by IDs.
func (_u *StorageLocationUpdateOne) AddCacheEntryIDs(ids ...string) *StorageLocationUpdateOne {
	_u.mutation.AddCacheEntryIDs(ids...)
	return _u
}

// AddCacheEntries adds the "cacheEntries" edges to the CacheEntry entity.
func (_u *StorageLocationUpdateOne) AddCacheEntries(v ...*CacheEntry) *StorageLocationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCacheEntryIDs(ids...)
}

// AddReaderLeaseIDs adds the "readerLeases" edge to the StorageReaderLease entity by IDs.
func (_u *StorageLocationUpdateOne) AddReaderLeaseIDs(ids ...string) *StorageLocationUpdateOne {
	_u.mutation.AddReaderLeaseIDs(ids...)
	return _u
}

// AddReaderLeases adds the "readerLeases" edges to the StorageReaderLease entity.
func (_u *StorageLocationUpdateOne) AddReaderLeases(v ...*StorageReaderLease) *StorageLocationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReaderLeaseIDs(ids...)
}

// Mutation returns the StorageLocationMutation object of the builder.
func (_u *StorageLocationUpdateOne) Mutation() *StorageLocationMutation {
	return _u.mutation
}

// ClearCacheEntries clears all "cacheEntries" edges to the CacheEntry entity.
func (_u *StorageLocationUpdateOne) ClearCacheEntries() *StorageLocationUpdateOne {
	_u.mutation.ClearCacheEntries()
	return _u
}

// RemoveCacheEntryIDs removes the "cacheEntries" edge to CacheEntry entities by IDs.
func (_u *StorageLocationUpdateOne) RemoveCacheEntryIDs(ids ...string) *StorageLocationUpdateOne {
	_u.mutation.RemoveCacheEntryIDs(ids...)
	return _u
}

// RemoveCacheEntries removes "cacheEntries" edges to CacheEntry entities.
func (_u *StorageLocationUpdateOne) RemoveCacheEntries(v ...*CacheEntry) *StorageLocationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCacheEntryIDs(ids...)
}

// ClearReaderLeases clears all "readerLeases" edges to the StorageReaderLease entity.
func (_u *StorageLocationUpdateOne) ClearReaderLeases() *StorageLocationUpdateOne {
	_u.mutation.ClearReaderLeases()
	return _u
}

// RemoveReaderLeaseIDs removes the "readerLeases" edge to StorageReaderLease entities by IDs.
func (_u *StorageLocationUpdateOne) RemoveReaderLeaseIDs(ids ...string) *StorageLocationUpdateOne {
	_u.mutation.RemoveReaderLeaseIDs(ids...)
	return _u
}

// RemoveReaderLeases removes "readerLeases" edges to StorageReaderLease entities.
func (_u *StorageLocationUpdateOne) RemoveReaderLeases(v ...*StorageReaderLease) *StorageLocationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReaderLeaseIDs(ids...)
}

// Where appends a list predicates to the StorageLocationUpdate builder.
func (_u *StorageLocationUpdateOne) Where(ps ...predicate.StorageLocation) *StorageLocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StorageLocationUpdateOne) Select(field string, fields ...string) *StorageLocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StorageLocation entity.
func (_u *StorageLocationUpdateOne) Save(ctx context.Context) (*StorageLocation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageLocationUpdateOne) SaveX(ctx context.Context) *StorageLocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StorageLocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageLocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageLocationUpdateOne) check() error {
	if v, ok := _u.mutation.FolderName(); ok {
		if err := storagelocation.FolderNameValidator(v); err != nil {
			return &ValidationError{Name: "folderName", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.folderName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PartCount(); ok {
		if err := storagelocation.PartCountValidator(v); err != nil {
			return &ValidationError{Name: "partCount", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.partCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := storagelocation.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "sizeBytes", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.sizeBytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseVersion(); ok {
		if err := storagelocation.LeaseVersionValidator(v); err != nil {
			return &ValidationError{Name: "leaseVersion", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.leaseVersion": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecencyAt(); ok {
		if err := storagelocation.RecencyAtValidator(v); err != nil {
			return &ValidationError{Name: "recencyAt", err: fmt.Errorf(`ent: validator failed for field "StorageLocation.recencyAt": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageLocationUpdateOne) sqlSave(ctx context.Context) (_node *StorageLocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagelocation.Table, storagelocation.Columns, sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StorageLocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagelocation.FieldID)
		for _, f := range fields {
			if !storagelocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storagelocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(storagelocation.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PartCount(); ok {
		_spec.SetField(storagelocation.FieldPartCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPartCount(); ok {
		_spec.AddField(storagelocation.FieldPartCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(storagelocation.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(storagelocation.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.SizeBytesCleared() {
		_spec.ClearField(storagelocation.FieldSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.LeaseVersion(); ok {
		_spec.SetField(storagelocation.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseVersion(); ok {
		_spec.AddField(storagelocation.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletionRequestedAt(); ok {
		_spec.SetField(storagelocation.FieldDeletionRequestedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletionRequestedAt(); ok {
		_spec.AddField(storagelocation.FieldDeletionRequestedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletionRequestedAtCleared() {
		_spec.ClearField(storagelocation.FieldDeletionRequestedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MergeStartedAt(); ok {
		_spec.SetField(storagelocation.FieldMergeStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMergeStartedAt(); ok {
		_spec.AddField(storagelocation.FieldMergeStartedAt, field.TypeInt64, value)
	}
	if _u.mutation.MergeStartedAtCleared() {
		_spec.ClearField(storagelocation.FieldMergeStartedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MergeLeaseToken(); ok {
		_spec.SetField(storagelocation.FieldMergeLeaseToken, field.TypeString, value)
	}
	if _u.mutation.MergeLeaseTokenCleared() {
		_spec.ClearField(storagelocation.FieldMergeLeaseToken, field.TypeString)
	}
	if value, ok := _u.mutation.MergeLeaseExpiresAt(); ok {
		_spec.SetField(storagelocation.FieldMergeLeaseExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMergeLeaseExpiresAt(); ok {
		_spec.AddField(storagelocation.FieldMergeLeaseExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.MergeLeaseExpiresAtCleared() {
		_spec.ClearField(storagelocation.FieldMergeLeaseExpiresAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MergedAt(); ok {
		_spec.SetField(storagelocation.FieldMergedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMergedAt(); ok {
		_spec.AddField(storagelocation.FieldMergedAt, field.TypeInt64, value)
	}
	if _u.mutation.MergedAtCleared() {
		_spec.ClearField(storagelocation.FieldMergedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaterializationUnsupportedAt(); ok {
		_spec.SetField(storagelocation.FieldMaterializationUnsupportedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaterializationUnsupportedAt(); ok {
		_spec.AddField(storagelocation.FieldMaterializationUnsupportedAt, field.TypeInt64, value)
	}
	if _u.mutation.MaterializationUnsupportedAtCleared() {
		_spec.ClearField(storagelocation.FieldMaterializationUnsupportedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.PartsDeletedAt(); ok {
		_spec.SetField(storagelocation.FieldPartsDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPartsDeletedAt(); ok {
		_spec.AddField(storagelocation.FieldPartsDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.PartsDeletedAtCleared() {
		_spec.ClearField(storagelocation.FieldPartsDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastDownloadedAt(); ok {
		_spec.SetField(storagelocation.FieldLastDownloadedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDownloadedAt(); ok {
		_spec.AddField(storagelocation.FieldLastDownloadedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastDownloadedAtCleared() {
		_spec.ClearField(storagelocation.FieldLastDownloadedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.RecencyAt(); ok {
		_spec.SetField(storagelocation.FieldRecencyAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecencyAt(); ok {
		_spec.AddField(storagelocation.FieldRecencyAt, field.TypeInt64, value)
	}
	if _u.mutation.CacheEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.CacheEntriesTable,
			Columns: []string{storagelocation.CacheEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCacheEntriesIDs(); len(nodes) > 0 && !_u.mutation.CacheEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.CacheEntriesTable,
			Columns: []string{storagelocation.CacheEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CacheEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.CacheEntriesTable,
			Columns: []string{storagelocation.CacheEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cacheentry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReaderLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.ReaderLeasesTable,
			Columns: []string{storagelocation.ReaderLeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReaderLeasesIDs(); len(nodes) > 0 && !_u.mutation.ReaderLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.ReaderLeasesTable,
			Columns: []string{storagelocation.ReaderLeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReaderLeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   storagelocation.ReaderLeasesTable,
			Columns: []string{storagelocation.ReaderLeasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagereaderlease.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StorageLocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagelocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
