// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagereaderlease"
)

// StorageReaderLease is the model entity for the StorageReaderLease schema.
type StorageReaderLease struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// StorageLocationId holds the value of the "storageLocationId" field.
	StorageLocationId string `json:"storageLocationId,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope storagereaderlease.Scope `json:"scope,omitempty"`
	// ExpiresAt holds the value of the "expiresAt" field.
	ExpiresAt int64 `json:"expiresAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StorageReaderLeaseQuery when eager-loading is set.
	Edges        StorageReaderLeaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StorageReaderLeaseEdges holds the relations/edges for other nodes in the graph.
type StorageReaderLeaseEdges struct {
	// StorageLocation holds the value of the storageLocation edge.
	StorageLocation *StorageLocation `json:"storageLocation,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StorageLocationOrErr returns the StorageLocation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StorageReaderLeaseEdges) StorageLocationOrErr() (*StorageLocation, error) {
	if e.StorageLocation != nil {
		return e.StorageLocation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: storagelocation.Label}
	}
	return nil, &NotLoadedError{edge: "storageLocation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StorageReaderLease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storagereaderlease.FieldExpiresAt:
			values[i] = new(sql.NullInt64)
		case storagereaderlease.FieldID, storagereaderlease.FieldStorageLocationId, storagereaderlease.FieldScope:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StorageReaderLease fields.
func (_m *StorageReaderLease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storagereaderlease.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case storagereaderlease.FieldStorageLocationId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storageLocationId", values[i])
			} else if value.Valid {
				_m.StorageLocationId = value.String
			}
		case storagereaderlease.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = storagereaderlease.Scope(value.String)
			}
		case storagereaderlease.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expiresAt", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StorageReaderLease.
// This includes values selected through modifiers, order, etc.
func (_m *StorageReaderLease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStorageLocation queries the "storageLocation" edge of the StorageReaderLease entity.
func (_m *StorageReaderLease) QueryStorageLocation() *StorageLocationQuery {
	return NewStorageReaderLeaseClient(_m.config).QueryStorageLocation(_m)
}

// Update returns a builder for updating this StorageReaderLease.
// Note that you need to call StorageReaderLease.Unwrap() before calling this method if this StorageReaderLease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StorageReaderLease) Update() *StorageReaderLeaseUpdateOne {
	return NewStorageReaderLeaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StorageReaderLease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StorageReaderLease) Unwrap() *StorageReaderLease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StorageReaderLease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StorageReaderLease) String() string {
	var builder strings.Builder
	builder.WriteString("StorageReaderLease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("storageLocationId=")
	builder.WriteString(_m.StorageLocationId)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scope))
	builder.WriteString(", ")
	builder.WriteString("expiresAt=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiresAt))
	builder.WriteByte(')')
	return builder.String()
}

// StorageReaderLeases is a parsable slice of StorageReaderLease.
type StorageReaderLeases []*StorageReaderLease
