// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagedeletion"
)

// StorageDeletion is the model entity for the StorageDeletion schema.
type StorageDeletion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// FolderName holds the value of the "folderName" field.
	FolderName string `json:"folderName,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt int64 `json:"createdAt,omitempty"`
	// AttemptCount holds the value of the "attemptCount" field.
	AttemptCount int `json:"attemptCount,omitempty"`
	// LastAttemptedAt holds the value of the "lastAttemptedAt" field.
	LastAttemptedAt *int64 `json:"lastAttemptedAt,omitempty"`
	// LastError holds the value of the "lastError" field.
	LastError    *string `json:"lastError,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StorageDeletion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storagedeletion.FieldID, storagedeletion.FieldCreatedAt, storagedeletion.FieldAttemptCount, storagedeletion.FieldLastAttemptedAt:
			values[i] = new(sql.NullInt64)
		case storagedeletion.FieldFolderName, storagedeletion.FieldLastError:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StorageDeletion fields.
func (_m *StorageDeletion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storagedeletion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case storagedeletion.FieldFolderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field folderName", values[i])
			} else if value.Valid {
				_m.FolderName = value.String
			}
		case storagedeletion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case storagedeletion.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attemptCount", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case storagedeletion.FieldLastAttemptedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lastAttemptedAt", values[i])
			} else if value.Valid {
				_m.LastAttemptedAt = new(int64)
				*_m.LastAttemptedAt = value.Int64
			}
		case storagedeletion.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lastError", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StorageDeletion.
// This includes values selected through modifiers, order, etc.
func (_m *StorageDeletion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StorageDeletion.
// Note that you need to call StorageDeletion.Unwrap() before calling this method if this StorageDeletion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StorageDeletion) Update() *StorageDeletionUpdateOne {
	return NewStorageDeletionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StorageDeletion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StorageDeletion) Unwrap() *StorageDeletion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StorageDeletion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StorageDeletion) String() string {
	var builder strings.Builder
	builder.WriteString("StorageDeletion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("folderName=")
	builder.WriteString(_m.FolderName)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("attemptCount=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	if v := _m.LastAttemptedAt; v != nil {
		builder.WriteString("lastAttemptedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("lastError=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// StorageDeletions is a parsable slice of StorageDeletion.
type StorageDeletions []*StorageDeletion
