// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/storagelocation"
)

// StorageLocation is the model entity for the StorageLocation schema.
type StorageLocation struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// FolderName holds the value of the "folderName" field.
	FolderName string `json:"folderName,omitempty"`
	// PartCount holds the value of the "partCount" field.
	PartCount int `json:"partCount,omitempty"`
	// SizeBytes holds the value of the "sizeBytes" field.
	SizeBytes *int64 `json:"sizeBytes,omitempty"`
	// LeaseVersion holds the value of the "leaseVersion" field.
	LeaseVersion int64 `json:"leaseVersion,omitempty"`
	// DeletionRequestedAt holds the value of the "deletionRequestedAt" field.
	DeletionRequestedAt *int64 `json:"deletionRequestedAt,omitempty"`
	// MergeStartedAt holds the value of the "mergeStartedAt" field.
	MergeStartedAt *int64 `json:"mergeStartedAt,omitempty"`
	// MergeLeaseToken holds the value of the "mergeLeaseToken" field.
	MergeLeaseToken *string `json:"mergeLeaseToken,omitempty"`
	// MergeLeaseExpiresAt holds the value of the "mergeLeaseExpiresAt" field.
	MergeLeaseExpiresAt *int64 `json:"mergeLeaseExpiresAt,omitempty"`
	// MergedAt holds the value of the "mergedAt" field.
	MergedAt *int64 `json:"mergedAt,omitempty"`
	// MaterializationUnsupportedAt holds the value of the "materializationUnsupportedAt" field.
	MaterializationUnsupportedAt *int64 `json:"materializationUnsupportedAt,omitempty"`
	// PartsDeletedAt holds the value of the "partsDeletedAt" field.
	PartsDeletedAt *int64 `json:"partsDeletedAt,omitempty"`
	// LastDownloadedAt holds the value of the "lastDownloadedAt" field.
	LastDownloadedAt *int64 `json:"lastDownloadedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StorageLocationQuery when eager-loading is set.
	Edges        StorageLocationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StorageLocationEdges holds the relations/edges for other nodes in the graph.
type StorageLocationEdges struct {
	// CacheEntries holds the value of the cacheEntries edge.
	CacheEntries []*CacheEntry `json:"cacheEntries,omitempty"`
	// ReaderLeases holds the value of the readerLeases edge.
	ReaderLeases []*StorageReaderLease `json:"readerLeases,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CacheEntriesOrErr returns the CacheEntries value or an error if the edge
// was not loaded in eager-loading.
func (e StorageLocationEdges) CacheEntriesOrErr() ([]*CacheEntry, error) {
	if e.loadedTypes[0] {
		return e.CacheEntries, nil
	}
	return nil, &NotLoadedError{edge: "cacheEntries"}
}

// ReaderLeasesOrErr returns the ReaderLeases value or an error if the edge
// was not loaded in eager-loading.
func (e StorageLocationEdges) ReaderLeasesOrErr() ([]*StorageReaderLease, error) {
	if e.loadedTypes[1] {
		return e.ReaderLeases, nil
	}
	return nil, &NotLoadedError{edge: "readerLeases"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StorageLocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storagelocation.FieldPartCount, storagelocation.FieldSizeBytes, storagelocation.FieldLeaseVersion, storagelocation.FieldDeletionRequestedAt, storagelocation.FieldMergeStartedAt, storagelocation.FieldMergeLeaseExpiresAt, storagelocation.FieldMergedAt, storagelocation.FieldMaterializationUnsupportedAt, storagelocation.FieldPartsDeletedAt, storagelocation.FieldLastDownloadedAt:
			values[i] = new(sql.NullInt64)
		case storagelocation.FieldID, storagelocation.FieldFolderName, storagelocation.FieldMergeLeaseToken:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StorageLocation fields.
func (_m *StorageLocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storagelocation.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case storagelocation.FieldFolderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field folderName", values[i])
			} else if value.Valid {
				_m.FolderName = value.String
			}
		case storagelocation.FieldPartCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field partCount", values[i])
			} else if value.Valid {
				_m.PartCount = int(value.Int64)
			}
		case storagelocation.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sizeBytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = new(int64)
				*_m.SizeBytes = value.Int64
			}
		case storagelocation.FieldLeaseVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field leaseVersion", values[i])
			} else if value.Valid {
				_m.LeaseVersion = value.Int64
			}
		case storagelocation.FieldDeletionRequestedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deletionRequestedAt", values[i])
			} else if value.Valid {
				_m.DeletionRequestedAt = new(int64)
				*_m.DeletionRequestedAt = value.Int64
			}
		case storagelocation.FieldMergeStartedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mergeStartedAt", values[i])
			} else if value.Valid {
				_m.MergeStartedAt = new(int64)
				*_m.MergeStartedAt = value.Int64
			}
		case storagelocation.FieldMergeLeaseToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mergeLeaseToken", values[i])
			} else if value.Valid {
				_m.MergeLeaseToken = new(string)
				*_m.MergeLeaseToken = value.String
			}
		case storagelocation.FieldMergeLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mergeLeaseExpiresAt", values[i])
			} else if value.Valid {
				_m.MergeLeaseExpiresAt = new(int64)
				*_m.MergeLeaseExpiresAt = value.Int64
			}
		case storagelocation.FieldMergedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mergedAt", values[i])
			} else if value.Valid {
				_m.MergedAt = new(int64)
				*_m.MergedAt = value.Int64
			}
		case storagelocation.FieldMaterializationUnsupportedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field materializationUnsupportedAt", values[i])
			} else if value.Valid {
				_m.MaterializationUnsupportedAt = new(int64)
				*_m.MaterializationUnsupportedAt = value.Int64
			}
		case storagelocation.FieldPartsDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field partsDeletedAt", values[i])
			} else if value.Valid {
				_m.PartsDeletedAt = new(int64)
				*_m.PartsDeletedAt = value.Int64
			}
		case storagelocation.FieldLastDownloadedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lastDownloadedAt", values[i])
			} else if value.Valid {
				_m.LastDownloadedAt = new(int64)
				*_m.LastDownloadedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StorageLocation.
// This includes values selected through modifiers, order, etc.
func (_m *StorageLocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCacheEntries queries the "cacheEntries" edge of the StorageLocation entity.
func (_m *StorageLocation) QueryCacheEntries() *CacheEntryQuery {
	return NewStorageLocationClient(_m.config).QueryCacheEntries(_m)
}

// QueryReaderLeases queries the "readerLeases" edge of the StorageLocation entity.
func (_m *StorageLocation) QueryReaderLeases() *StorageReaderLeaseQuery {
	return NewStorageLocationClient(_m.config).QueryReaderLeases(_m)
}

// Update returns a builder for updating this StorageLocation.
// Note that you need to call StorageLocation.Unwrap() before calling this method if this StorageLocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StorageLocation) Update() *StorageLocationUpdateOne {
	return NewStorageLocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StorageLocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StorageLocation) Unwrap() *StorageLocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StorageLocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StorageLocation) String() string {
	var builder strings.Builder
	builder.WriteString("StorageLocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("folderName=")
	builder.WriteString(_m.FolderName)
	builder.WriteString(", ")
	builder.WriteString("partCount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PartCount))
	builder.WriteString(", ")
	if v := _m.SizeBytes; v != nil {
		builder.WriteString("sizeBytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("leaseVersion=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeaseVersion))
	builder.WriteString(", ")
	if v := _m.DeletionRequestedAt; v != nil {
		builder.WriteString("deletionRequestedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MergeStartedAt; v != nil {
		builder.WriteString("mergeStartedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MergeLeaseToken; v != nil {
		builder.WriteString("mergeLeaseToken=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MergeLeaseExpiresAt; v != nil {
		builder.WriteString("mergeLeaseExpiresAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MergedAt; v != nil {
		builder.WriteString("mergedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaterializationUnsupportedAt; v != nil {
		builder.WriteString("materializationUnsupportedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PartsDeletedAt; v != nil {
		builder.WriteString("partsDeletedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastDownloadedAt; v != nil {
		builder.WriteString("lastDownloadedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// StorageLocations is a parsable slice of StorageLocation.
type StorageLocations []*StorageLocation
