// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/upload"
)

// UploadCreate is the builder for creating a Upload entity.
type UploadCreate struct {
	config
	mutation *UploadMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *UploadCreate) SetKey(v string) *UploadCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *UploadCreate) SetVersion(v string) *UploadCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *UploadCreate) SetScope(v string) *UploadCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetRepoId sets the "repoId" field.
func (_c *UploadCreate) SetRepoId(v string) *UploadCreate {
	_c.mutation.SetRepoId(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *UploadCreate) SetCreatedAt(v int64) *UploadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetLastPartUploadedAt sets the "lastPartUploadedAt" field.
func (_c *UploadCreate) SetLastPartUploadedAt(v int64) *UploadCreate {
	_c.mutation.SetLastPartUploadedAt(v)
	return _c
}

// SetNillableLastPartUploadedAt sets the "lastPartUploadedAt" field if the given value is not nil.
func (_c *UploadCreate) SetNillableLastPartUploadedAt(v *int64) *UploadCreate {
	if v != nil {
		_c.SetLastPartUploadedAt(*v)
	}
	return _c
}

// SetStartedPartUploadCount sets the "startedPartUploadCount" field.
func (_c *UploadCreate) SetStartedPartUploadCount(v int) *UploadCreate {
	_c.mutation.SetStartedPartUploadCount(v)
	return _c
}

// SetNillableStartedPartUploadCount sets the "startedPartUploadCount" field if the given value is not nil.
func (_c *UploadCreate) SetNillableStartedPartUploadCount(v *int) *UploadCreate {
	if v != nil {
		_c.SetStartedPartUploadCount(*v)
	}
	return _c
}

// SetFinishedPartUploadCount sets the "finishedPartUploadCount" field.
func (_c *UploadCreate) SetFinishedPartUploadCount(v int) *UploadCreate {
	_c.mutation.SetFinishedPartUploadCount(v)
	return _c
}

// SetNillableFinishedPartUploadCount sets the "finishedPartUploadCount" field if the given value is not nil.
func (_c *UploadCreate) SetNillableFinishedPartUploadCount(v *int) *UploadCreate {
	if v != nil {
		_c.SetFinishedPartUploadCount(*v)
	}
	return _c
}

// SetFolderName sets the "folderName" field.
func (_c *UploadCreate) SetFolderName(v string) *UploadCreate {
	_c.mutation.SetFolderName(v)
	return _c
}

// SetCommittedPartCount sets the "committedPartCount" field.
func (_c *UploadCreate) SetCommittedPartCount(v int) *UploadCreate {
	_c.mutation.SetCommittedPartCount(v)
	return _c
}

// SetNillableCommittedPartCount sets the "committedPartCount" field if the given value is not nil.
func (_c *UploadCreate) SetNillableCommittedPartCount(v *int) *UploadCreate {
	if v != nil {
		_c.SetCommittedPartCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UploadCreate) SetID(v int64) *UploadCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UploadMutation object of the builder.
func (_c *UploadCreate) Mutation() *UploadMutation {
	return _c.mutation
}

// Save creates the Upload in the database.
func (_c *UploadCreate) Save(ctx context.Context) (*Upload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UploadCreate) SaveX(ctx context.Context) *Upload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UploadCreate) defaults() {
	if _, ok := _c.mutation.StartedPartUploadCount(); !ok {
		v := upload.DefaultStartedPartUploadCount
		_c.mutation.SetStartedPartUploadCount(v)
	}
	if _, ok := _c.mutation.FinishedPartUploadCount(); !ok {
		v := upload.DefaultFinishedPartUploadCount
		_c.mutation.SetFinishedPartUploadCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UploadCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Upload.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := upload.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Upload.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Upload.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := upload.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Upload.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Upload.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := upload.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Upload.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepoId(); !ok {
		return &ValidationError{Name: "repoId", err: errors.New(`ent: missing required field "Upload.repoId"`)}
	}
	if v, ok := _c.mutation.RepoId(); ok {
		if err := upload.RepoIdValidator(v); err != nil {
			return &ValidationError{Name: "repoId", err: fmt.Errorf(`ent: validator failed for field "Upload.repoId": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Upload.createdAt"`)}
	}
	if _, ok := _c.mutation.StartedPartUploadCount(); !ok {
		return &ValidationError{Name: "startedPartUploadCount", err: errors.New(`ent: missing required field "Upload.startedPartUploadCount"`)}
	}
	if v, ok := _c.mutation.StartedPartUploadCount(); ok {
		if err := upload.StartedPartUploadCountValidator(v); err != nil {
			return &ValidationError{Name: "startedPartUploadCount", err: fmt.Errorf(`ent: validator failed for field "Upload.startedPartUploadCount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FinishedPartUploadCount(); !ok {
		return &ValidationError{Name: "finishedPartUploadCount", err: errors.New(`ent: missing required field "Upload.finishedPartUploadCount"`)}
	}
	if v, ok := _c.mutation.FinishedPartUploadCount(); ok {
		if err := upload.FinishedPartUploadCountValidator(v); err != nil {
			return &ValidationError{Name: "finishedPartUploadCount", err: fmt.Errorf(`ent: validator failed for field "Upload.finishedPartUploadCount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FolderName(); !ok {
		return &ValidationError{Name: "folderName", err: errors.New(`ent: missing required field "Upload.folderName"`)}
	}
	if v, ok := _c.mutation.FolderName(); ok {
		if err := upload.FolderNameValidator(v); err != nil {
			return &ValidationError{Name: "folderName", err: fmt.Errorf(`ent: validator failed for field "Upload.folderName": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CommittedPartCount(); ok {
		if err := upload.CommittedPartCountValidator(v); err != nil {
			return &ValidationError{Name: "committedPartCount", err: fmt.Errorf(`ent: validator failed for field "Upload.committedPartCount": %w`, err)}
		}
	}
	return nil
}

func (_c *UploadCreate) sqlSave(ctx context.Context) (*Upload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UploadCreate) createSpec() (*Upload, *sqlgraph.CreateSpec) {
	var (
		_node = &Upload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upload.Table, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(upload.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(upload.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(upload.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.RepoId(); ok {
		_spec.SetField(upload.FieldRepoId, field.TypeString, value)
		_node.RepoId = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upload.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastPartUploadedAt(); ok {
		_spec.SetField(upload.FieldLastPartUploadedAt, field.TypeInt64, value)
		_node.LastPartUploadedAt = &value
	}
	if value, ok := _c.mutation.StartedPartUploadCount(); ok {
		_spec.SetField(upload.FieldStartedPartUploadCount, field.TypeInt, value)
		_node.StartedPartUploadCount = value
	}
	if value, ok := _c.mutation.FinishedPartUploadCount(); ok {
		_spec.SetField(upload.FieldFinishedPartUploadCount, field.TypeInt, value)
		_node.FinishedPartUploadCount = value
	}
	if value, ok := _c.mutation.FolderName(); ok {
		_spec.SetField(upload.FieldFolderName, field.TypeString, value)
		_node.FolderName = value
	}
	if value, ok := _c.mutation.CommittedPartCount(); ok {
		_spec.SetField(upload.FieldCommittedPartCount, field.TypeInt, value)
		_node.CommittedPartCount = &value
	}
	return _node, _spec
}

// UploadCreateBulk is the builder for creating many Upload entities in bulk.
type UploadCreateBulk struct {
	config
	err      error
	builders []*UploadCreate
}

// Save creates the Upload entities in the database.
func (_c *UploadCreateBulk) Save(ctx context.Context) ([]*Upload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Upload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UploadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UploadCreateBulk) SaveX(ctx context.Context) []*Upload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
