// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/upload"
)

// Upload is the model entity for the Upload schema.
type Upload struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// RepoId holds the value of the "repoId" field.
	RepoId string `json:"repoId,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt int64 `json:"createdAt,omitempty"`
	// LastPartUploadedAt holds the value of the "lastPartUploadedAt" field.
	LastPartUploadedAt *int64 `json:"lastPartUploadedAt,omitempty"`
	// StartedPartUploadCount holds the value of the "startedPartUploadCount" field.
	StartedPartUploadCount int `json:"startedPartUploadCount,omitempty"`
	// FinishedPartUploadCount holds the value of the "finishedPartUploadCount" field.
	FinishedPartUploadCount int `json:"finishedPartUploadCount,omitempty"`
	// FolderName holds the value of the "folderName" field.
	FolderName string `json:"folderName,omitempty"`
	// CommittedPartCount holds the value of the "committedPartCount" field.
	CommittedPartCount *int `json:"committedPartCount,omitempty"`
	// TupleHash holds the value of the "tupleHash" field.
	TupleHash    *string `json:"tupleHash,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Upload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upload.FieldID, upload.FieldCreatedAt, upload.FieldLastPartUploadedAt, upload.FieldStartedPartUploadCount, upload.FieldFinishedPartUploadCount, upload.FieldCommittedPartCount:
			values[i] = new(sql.NullInt64)
		case upload.FieldKey, upload.FieldVersion, upload.FieldScope, upload.FieldRepoId, upload.FieldFolderName, upload.FieldTupleHash:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Upload fields.
func (_m *Upload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upload.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upload.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case upload.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case upload.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case upload.FieldRepoId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repoId", values[i])
			} else if value.Valid {
				_m.RepoId = value.String
			}
		case upload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case upload.FieldLastPartUploadedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lastPartUploadedAt", values[i])
			} else if value.Valid {
				_m.LastPartUploadedAt = new(int64)
				*_m.LastPartUploadedAt = value.Int64
			}
		case upload.FieldStartedPartUploadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field startedPartUploadCount", values[i])
			} else if value.Valid {
				_m.StartedPartUploadCount = int(value.Int64)
			}
		case upload.FieldFinishedPartUploadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field finishedPartUploadCount", values[i])
			} else if value.Valid {
				_m.FinishedPartUploadCount = int(value.Int64)
			}
		case upload.FieldFolderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field folderName", values[i])
			} else if value.Valid {
				_m.FolderName = value.String
			}
		case upload.FieldCommittedPartCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field committedPartCount", values[i])
			} else if value.Valid {
				_m.CommittedPartCount = new(int)
				*_m.CommittedPartCount = int(value.Int64)
			}
		case upload.FieldTupleHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tupleHash", values[i])
			} else if value.Valid {
				_m.TupleHash = new(string)
				*_m.TupleHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Upload.
// This includes values selected through modifiers, order, etc.
func (_m *Upload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Upload.
// Note that you need to call Upload.Unwrap() before calling this method if this Upload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Upload) Update() *UploadUpdateOne {
	return NewUploadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Upload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Upload) Unwrap() *Upload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Upload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Upload) String() string {
	var builder strings.Builder
	builder.WriteString("Upload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("repoId=")
	builder.WriteString(_m.RepoId)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	if v := _m.LastPartUploadedAt; v != nil {
		builder.WriteString("lastPartUploadedAt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("startedPartUploadCount=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartedPartUploadCount))
	builder.WriteString(", ")
	builder.WriteString("finishedPartUploadCount=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinishedPartUploadCount))
	builder.WriteString(", ")
	builder.WriteString("folderName=")
	builder.WriteString(_m.FolderName)
	builder.WriteString(", ")
	if v := _m.CommittedPartCount; v != nil {
		builder.WriteString("committedPartCount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TupleHash; v != nil {
		builder.WriteString("tupleHash=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Uploads is a parsable slice of Upload.
type Uploads []*Upload
