// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/upload"
)

// UploadUpdate is the builder for updating Upload entities.
type UploadUpdate struct {
	config
	hooks    []Hook
	mutation *UploadMutation
}

// Where appends a list predicates to the UploadUpdate builder.
func (_u *UploadUpdate) Where(ps ...predicate.Upload) *UploadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *UploadUpdate) SetKey(v string) *UploadUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableKey(v *string) *UploadUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *UploadUpdate) SetVersion(v string) *UploadUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableVersion(v *string) *UploadUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *UploadUpdate) SetScope(v string) *UploadUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableScope(v *string) *UploadUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetRepoId sets the "repoId" field.
func (_u *UploadUpdate) SetRepoId(v string) *UploadUpdate {
	_u.mutation.SetRepoId(v)
	return _u
}

// SetNillableRepoId sets the "repoId" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableRepoId(v *string) *UploadUpdate {
	if v != nil {
		_u.SetRepoId(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *UploadUpdate) SetCreatedAt(v int64) *UploadUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableCreatedAt(v *int64) *UploadUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "createdAt" field.
func (_u *UploadUpdate) AddCreatedAt(v int64) *UploadUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetLastPartUploadedAt sets the "lastPartUploadedAt" field.
func (_u *UploadUpdate) SetLastPartUploadedAt(v int64) *UploadUpdate {
	_u.mutation.ResetLastPartUploadedAt()
	_u.mutation.SetLastPartUploadedAt(v)
	return _u
}

// SetNillableLastPartUploadedAt sets the "lastPartUploadedAt" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableLastPartUploadedAt(v *int64) *UploadUpdate {
	if v != nil {
		_u.SetLastPartUploadedAt(*v)
	}
	return _u
}

// AddLastPartUploadedAt adds value to the "lastPartUploadedAt" field.
func (_u *UploadUpdate) AddLastPartUploadedAt(v int64) *UploadUpdate {
	_u.mutation.AddLastPartUploadedAt(v)
	return _u
}

// ClearLastPartUploadedAt clears the value of the "lastPartUploadedAt" field.
func (_u *UploadUpdate) ClearLastPartUploadedAt() *UploadUpdate {
	_u.mutation.ClearLastPartUploadedAt()
	return _u
}

// SetStartedPartUploadCount sets the "startedPartUploadCount" field.
func (_u *UploadUpdate) SetStartedPartUploadCount(v int) *UploadUpdate {
	_u.mutation.ResetStartedPartUploadCount()
	_u.mutation.SetStartedPartUploadCount(v)
	return _u
}

// SetNillableStartedPartUploadCount sets the "startedPartUploadCount" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableStartedPartUploadCount(v *int) *UploadUpdate {
	if v != nil {
		_u.SetStartedPartUploadCount(*v)
	}
	return _u
}

// AddStartedPartUploadCount adds value to the "startedPartUploadCount" field.
func (_u *UploadUpdate) AddStartedPartUploadCount(v int) *UploadUpdate {
	_u.mutation.AddStartedPartUploadCount(v)
	return _u
}

// SetFinishedPartUploadCount sets the "finishedPartUploadCount" field.
func (_u *UploadUpdate) SetFinishedPartUploadCount(v int) *UploadUpdate {
	_u.mutation.ResetFinishedPartUploadCount()
	_u.mutation.SetFinishedPartUploadCount(v)
	return _u
}

// SetNillableFinishedPartUploadCount sets the "finishedPartUploadCount" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableFinishedPartUploadCount(v *int) *UploadUpdate {
	if v != nil {
		_u.SetFinishedPartUploadCount(*v)
	}
	return _u
}

// AddFinishedPartUploadCount adds value to the "finishedPartUploadCount" field.
func (_u *UploadUpdate) AddFinishedPartUploadCount(v int) *UploadUpdate {
	_u.mutation.AddFinishedPartUploadCount(v)
	return _u
}

// SetFolderName sets the "folderName" field.
func (_u *UploadUpdate) SetFolderName(v string) *UploadUpdate {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folderName" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableFolderName(v *string) *UploadUpdate {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetCommittedPartCount sets the "committedPartCount" field.
func (_u *UploadUpdate) SetCommittedPartCount(v int) *UploadUpdate {
	_u.mutation.ResetCommittedPartCount()
	_u.mutation.SetCommittedPartCount(v)
	return _u
}

// SetNillableCommittedPartCount sets the "committedPartCount" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableCommittedPartCount(v *int) *UploadUpdate {
	if v != nil {
		_u.SetCommittedPartCount(*v)
	}
	return _u
}

// AddCommittedPartCount adds value to the "committedPartCount" field.
func (_u *UploadUpdate) AddCommittedPartCount(v int) *UploadUpdate {
	_u.mutation.AddCommittedPartCount(v)
	return _u
}

// ClearCommittedPartCount clears the value of the "committedPartCount" field.
func (_u *UploadUpdate) ClearCommittedPartCount() *UploadUpdate {
	_u.mutation.ClearCommittedPartCount()
	return _u
}

// SetTupleHash sets the "tupleHash" field.
func (_u *UploadUpdate) SetTupleHash(v string) *UploadUpdate {
	_u.mutation.SetTupleHash(v)
	return _u
}

// SetNillableTupleHash sets the "tupleHash" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableTupleHash(v *string) *UploadUpdate {
	if v != nil {
		_u.SetTupleHash(*v)
	}
	return _u
}

// ClearTupleHash clears the value of the "tupleHash" field.
func (_u *UploadUpdate) ClearTupleHash() *UploadUpdate {
	_u.mutation.ClearTupleHash()
	return _u
}

// Mutation returns the UploadMutation object of the builder.
func (_u *UploadUpdate) Mutation() *UploadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UploadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UploadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := upload.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Upload.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := upload.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Upload.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := upload.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Upload.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoId(); ok {
		if err := upload.RepoIdValidator(v); err != nil {
			return &ValidationError{Name: "repoId", err: fmt.Errorf(`ent: validator failed for field "Upload.repoId": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StartedPartUploadCount(); ok {
		if err := upload.StartedPartUploadCountValidator(v); err != nil {
			return &ValidationError{Name: "startedPartUploadCount", err: fmt.Errorf(`ent: validator failed for field "Upload.startedPartUploadCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinishedPartUploadCount(); ok {
		if err := upload.FinishedPartUploadCountValidator(v); err != nil {
			return &ValidationError{Name: "finishedPartUploadCount", err: fmt.Errorf(`ent: validator failed for field "Upload.finishedPartUploadCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FolderName(); ok {
		if err := upload.FolderNameValidator(v); err != nil {
			return &ValidationError{Name: "folderName", err: fmt.Errorf(`ent: validator failed for field "Upload.folderName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommittedPartCount(); ok {
		if err := upload.CommittedPartCountValidator(v); err != nil {
			return &ValidationError{Name: "committedPartCount", err: fmt.Errorf(`ent: validator failed for field "Upload.committedPartCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TupleHash(); ok {
		if err := upload.TupleHashValidator(v); err != nil {
			return &ValidationError{Name: "tupleHash", err: fmt.Errorf(`ent: validator failed for field "Upload.tupleHash": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(upload.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(upload.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(upload.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoId(); ok {
		_spec.SetField(upload.FieldRepoId, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(upload.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(upload.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastPartUploadedAt(); ok {
		_spec.SetField(upload.FieldLastPartUploadedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastPartUploadedAt(); ok {
		_spec.AddField(upload.FieldLastPartUploadedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastPartUploadedAtCleared() {
		_spec.ClearField(upload.FieldLastPartUploadedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartedPartUploadCount(); ok {
		_spec.SetField(upload.FieldStartedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartedPartUploadCount(); ok {
		_spec.AddField(upload.FieldStartedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FinishedPartUploadCount(); ok {
		_spec.SetField(upload.FieldFinishedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinishedPartUploadCount(); ok {
		_spec.AddField(upload.FieldFinishedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(upload.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommittedPartCount(); ok {
		_spec.SetField(upload.FieldCommittedPartCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommittedPartCount(); ok {
		_spec.AddField(upload.FieldCommittedPartCount, field.TypeInt, value)
	}
	if _u.mutation.CommittedPartCountCleared() {
		_spec.ClearField(upload.FieldCommittedPartCount, field.TypeInt)
	}
	if value, ok := _u.mutation.TupleHash(); ok {
		_spec.SetField(upload.FieldTupleHash, field.TypeString, value)
	}
	if _u.mutation.TupleHashCleared() {
		_spec.ClearField(upload.FieldTupleHash, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UploadUpdateOne is the builder for updating a single Upload entity.
type UploadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UploadMutation
}

// SetKey sets the "key" field.
func (_u *UploadUpdateOne) SetKey(v string) *UploadUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableKey(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *UploadUpdateOne) SetVersion(v string) *UploadUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableVersion(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *UploadUpdateOne) SetScope(v string) *UploadUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableScope(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetRepoId sets the "repoId" field.
func (_u *UploadUpdateOne) SetRepoId(v string) *UploadUpdateOne {
	_u.mutation.SetRepoId(v)
	return _u
}

// SetNillableRepoId sets the "repoId" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableRepoId(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetRepoId(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *UploadUpdateOne) SetCreatedAt(v int64) *UploadUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableCreatedAt(v *int64) *UploadUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "createdAt" field.
func (_u *UploadUpdateOne) AddCreatedAt(v int64) *UploadUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetLastPartUploadedAt sets the "lastPartUploadedAt" field.
func (_u *UploadUpdateOne) SetLastPartUploadedAt(v int64) *UploadUpdateOne {
	_u.mutation.ResetLastPartUploadedAt()
	_u.mutation.SetLastPartUploadedAt(v)
	return _u
}

// SetNillableLastPartUploadedAt sets the "lastPartUploadedAt" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableLastPartUploadedAt(v *int64) *UploadUpdateOne {
	if v != nil {
		_u.SetLastPartUploadedAt(*v)
	}
	return _u
}

// AddLastPartUploadedAt adds value to the "lastPartUploadedAt" field.
func (_u *UploadUpdateOne) AddLastPartUploadedAt(v int64) *UploadUpdateOne {
	_u.mutation.AddLastPartUploadedAt(v)
	return _u
}

// ClearLastPartUploadedAt clears the value of the "lastPartUploadedAt" field.
func (_u *UploadUpdateOne) ClearLastPartUploadedAt() *UploadUpdateOne {
	_u.mutation.ClearLastPartUploadedAt()
	return _u
}

// SetStartedPartUploadCount sets the "startedPartUploadCount" field.
func (_u *UploadUpdateOne) SetStartedPartUploadCount(v int) *UploadUpdateOne {
	_u.mutation.ResetStartedPartUploadCount()
	_u.mutation.SetStartedPartUploadCount(v)
	return _u
}

// SetNillableStartedPartUploadCount sets the "startedPartUploadCount" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableStartedPartUploadCount(v *int) *UploadUpdateOne {
	if v != nil {
		_u.SetStartedPartUploadCount(*v)
	}
	return _u
}

// AddStartedPartUploadCount adds value to the "startedPartUploadCount" field.
func (_u *UploadUpdateOne) AddStartedPartUploadCount(v int) *UploadUpdateOne {
	_u.mutation.AddStartedPartUploadCount(v)
	return _u
}

// SetFinishedPartUploadCount sets the "finishedPartUploadCount" field.
func (_u *UploadUpdateOne) SetFinishedPartUploadCount(v int) *UploadUpdateOne {
	_u.mutation.ResetFinishedPartUploadCount()
	_u.mutation.SetFinishedPartUploadCount(v)
	return _u
}

// SetNillableFinishedPartUploadCount sets the "finishedPartUploadCount" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableFinishedPartUploadCount(v *int) *UploadUpdateOne {
	if v != nil {
		_u.SetFinishedPartUploadCount(*v)
	}
	return _u
}

// AddFinishedPartUploadCount adds value to the "finishedPartUploadCount" field.
func (_u *UploadUpdateOne) AddFinishedPartUploadCount(v int) *UploadUpdateOne {
	_u.mutation.AddFinishedPartUploadCount(v)
	return _u
}

// SetFolderName sets the "folderName" field.
func (_u *UploadUpdateOne) SetFolderName(v string) *UploadUpdateOne {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folderName" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableFolderName(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetCommittedPartCount sets the "committedPartCount" field.
func (_u *UploadUpdateOne) SetCommittedPartCount(v int) *UploadUpdateOne {
	_u.mutation.ResetCommittedPartCount()
	_u.mutation.SetCommittedPartCount(v)
	return _u
}

// SetNillableCommittedPartCount sets the "committedPartCount" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableCommittedPartCount(v *int) *UploadUpdateOne {
	if v != nil {
		_u.SetCommittedPartCount(*v)
	}
	return _u
}

// AddCommittedPartCount adds value to the "committedPartCount" field.
func (_u *UploadUpdateOne) AddCommittedPartCount(v int) *UploadUpdateOne {
	_u.mutation.AddCommittedPartCount(v)
	return _u
}

// ClearCommittedPartCount clears the value of the "committedPartCount" field.
func (_u *UploadUpdateOne) ClearCommittedPartCount() *UploadUpdateOne {
	_u.mutation.ClearCommittedPartCount()
	return _u
}

// SetTupleHash sets the "tupleHash" field.
func (_u *UploadUpdateOne) SetTupleHash(v string) *UploadUpdateOne {
	_u.mutation.SetTupleHash(v)
	return _u
}

// SetNillableTupleHash sets the "tupleHash" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableTupleHash(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetTupleHash(*v)
	}
	return _u
}

// ClearTupleHash clears the value of the "tupleHash" field.
func (_u *UploadUpdateOne) ClearTupleHash() *UploadUpdateOne {
	_u.mutation.ClearTupleHash()
	return _u
}

// Mutation returns the UploadMutation object of the builder.
func (_u *UploadUpdateOne) Mutation() *UploadMutation {
	return _u.mutation
}

// Where appends a list predicates to the UploadUpdate builder.
func (_u *UploadUpdateOne) Where(ps ...predicate.Upload) *UploadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UploadUpdateOne) Select(field string, fields ...string) *UploadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Upload entity.
func (_u *UploadUpdateOne) Save(ctx context.Context) (*Upload, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadUpdateOne) SaveX(ctx context.Context) *Upload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UploadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := upload.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Upload.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := upload.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Upload.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := upload.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Upload.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoId(); ok {
		if err := upload.RepoIdValidator(v); err != nil {
			return &ValidationError{Name: "repoId", err: fmt.Errorf(`ent: validator failed for field "Upload.repoId": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StartedPartUploadCount(); ok {
		if err := upload.StartedPartUploadCountValidator(v); err != nil {
			return &ValidationError{Name: "startedPartUploadCount", err: fmt.Errorf(`ent: validator failed for field "Upload.startedPartUploadCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinishedPartUploadCount(); ok {
		if err := upload.FinishedPartUploadCountValidator(v); err != nil {
			return &ValidationError{Name: "finishedPartUploadCount", err: fmt.Errorf(`ent: validator failed for field "Upload.finishedPartUploadCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FolderName(); ok {
		if err := upload.FolderNameValidator(v); err != nil {
			return &ValidationError{Name: "folderName", err: fmt.Errorf(`ent: validator failed for field "Upload.folderName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommittedPartCount(); ok {
		if err := upload.CommittedPartCountValidator(v); err != nil {
			return &ValidationError{Name: "committedPartCount", err: fmt.Errorf(`ent: validator failed for field "Upload.committedPartCount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TupleHash(); ok {
		if err := upload.TupleHashValidator(v); err != nil {
			return &ValidationError{Name: "tupleHash", err: fmt.Errorf(`ent: validator failed for field "Upload.tupleHash": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadUpdateOne) sqlSave(ctx context.Context) (_node *Upload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Upload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upload.FieldID)
		for _, f := range fields {
			if !upload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(upload.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(upload.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(upload.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoId(); ok {
		_spec.SetField(upload.FieldRepoId, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(upload.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(upload.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastPartUploadedAt(); ok {
		_spec.SetField(upload.FieldLastPartUploadedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastPartUploadedAt(); ok {
		_spec.AddField(upload.FieldLastPartUploadedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastPartUploadedAtCleared() {
		_spec.ClearField(upload.FieldLastPartUploadedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartedPartUploadCount(); ok {
		_spec.SetField(upload.FieldStartedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartedPartUploadCount(); ok {
		_spec.AddField(upload.FieldStartedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FinishedPartUploadCount(); ok {
		_spec.SetField(upload.FieldFinishedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinishedPartUploadCount(); ok {
		_spec.AddField(upload.FieldFinishedPartUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(upload.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommittedPartCount(); ok {
		_spec.SetField(upload.FieldCommittedPartCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommittedPartCount(); ok {
		_spec.AddField(upload.FieldCommittedPartCount, field.TypeInt, value)
	}
	if _u.mutation.CommittedPartCountCleared() {
		_spec.ClearField(upload.FieldCommittedPartCount, field.TypeInt)
	}
	if value, ok := _u.mutation.TupleHash(); ok {
		_spec.SetField(upload.FieldTupleHash, field.TypeString, value)
	}
	if _u.mutation.TupleHashCleared() {
		_spec.ClearField(upload.FieldTupleHash, field.TypeString)
	}
	_node = &Upload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
