// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CacheEntry is the predicate function for cacheentry builders.
type CacheEntry func(*sql.Selector)

// StorageDeletion is the predicate function for storagedeletion builders.
type StorageDeletion func(*sql.Selector)

// StorageLocation is the predicate function for storagelocation builders.
type StorageLocation func(*sql.Selector)

// StorageReaderLease is the predicate function for storagereaderlease builders.
type StorageReaderLease func(*sql.Selector)

// Upload is the predicate function for upload builders.
type Upload func(*sql.Selector)
