// Code generated by ent, DO NOT EDIT.

package upload

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upload type in the database.
	Label = "upload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldRepoId holds the string denoting the repoid field in the database.
	FieldRepoId = "repoId"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// FieldLastPartUploadedAt holds the string denoting the lastpartuploadedat field in the database.
	FieldLastPartUploadedAt = "lastPartUploadedAt"
	// FieldStartedPartUploadCount holds the string denoting the startedpartuploadcount field in the database.
	FieldStartedPartUploadCount = "startedPartUploadCount"
	// FieldFinishedPartUploadCount holds the string denoting the finishedpartuploadcount field in the database.
	FieldFinishedPartUploadCount = "finishedPartUploadCount"
	// FieldFolderName holds the string denoting the foldername field in the database.
	FieldFolderName = "folderName"
	// FieldCommittedPartCount holds the string denoting the committedpartcount field in the database.
	FieldCommittedPartCount = "committedPartCount"
	// FieldTupleHash holds the string denoting the tuplehash field in the database.
	FieldTupleHash = "tupleHash"
	// Table holds the table name of the upload in the database.
	Table = "uploads"
)

// Columns holds all SQL columns for upload fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldVersion,
	FieldScope,
	FieldRepoId,
	FieldCreatedAt,
	FieldLastPartUploadedAt,
	FieldStartedPartUploadCount,
	FieldFinishedPartUploadCount,
	FieldFolderName,
	FieldCommittedPartCount,
	FieldTupleHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	ScopeValidator func(string) error
	// RepoIdValidator is a validator for the "repoId" field. It is called by the builders before save.
	RepoIdValidator func(string) error
	// DefaultStartedPartUploadCount holds the default value on creation for the "startedPartUploadCount" field.
	DefaultStartedPartUploadCount int
	// StartedPartUploadCountValidator is a validator for the "startedPartUploadCount" field. It is called by the builders before save.
	StartedPartUploadCountValidator func(int) error
	// DefaultFinishedPartUploadCount holds the default value on creation for the "finishedPartUploadCount" field.
	DefaultFinishedPartUploadCount int
	// FinishedPartUploadCountValidator is a validator for the "finishedPartUploadCount" field. It is called by the builders before save.
	FinishedPartUploadCountValidator func(int) error
	// FolderNameValidator is a validator for the "folderName" field. It is called by the builders before save.
	FolderNameValidator func(string) error
	// CommittedPartCountValidator is a validator for the "committedPartCount" field. It is called by the builders before save.
	CommittedPartCountValidator func(int) error
	// TupleHashValidator is a validator for the "tupleHash" field. It is called by the builders before save.
	TupleHashValidator func(string) error
)

// OrderOption defines the ordering options for the Upload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByRepoId orders the results by the repoId field.
func ByRepoId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoId, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLastPartUploadedAt orders the results by the lastPartUploadedAt field.
func ByLastPartUploadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPartUploadedAt, opts...).ToFunc()
}

// ByStartedPartUploadCount orders the results by the startedPartUploadCount field.
func ByStartedPartUploadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedPartUploadCount, opts...).ToFunc()
}

// ByFinishedPartUploadCount orders the results by the finishedPartUploadCount field.
func ByFinishedPartUploadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedPartUploadCount, opts...).ToFunc()
}

// ByFolderName orders the results by the folderName field.
func ByFolderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFolderName, opts...).ToFunc()
}

// ByCommittedPartCount orders the results by the committedPartCount field.
func ByCommittedPartCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommittedPartCount, opts...).ToFunc()
}

// ByTupleHash orders the results by the tupleHash field.
func ByTupleHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTupleHash, opts...).ToFunc()
}
