// Code generated by ent, DO NOT EDIT.

package upload

import (
	"entgo.io/ent/dialect/sql"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldKey, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldVersion, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldScope, v))
}

// RepoId applies equality check predicate on the "repoId" field. It's identical to RepoIdEQ.
func RepoId(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldRepoId, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCreatedAt, v))
}

// LastPartUploadedAt applies equality check predicate on the "lastPartUploadedAt" field. It's identical to LastPartUploadedAtEQ.
func LastPartUploadedAt(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldLastPartUploadedAt, v))
}

// StartedPartUploadCount applies equality check predicate on the "startedPartUploadCount" field. It's identical to StartedPartUploadCountEQ.
func StartedPartUploadCount(v int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldStartedPartUploadCount, v))
}

// FinishedPartUploadCount applies equality check predicate on the "finishedPartUploadCount" field. It's identical to FinishedPartUploadCountEQ.
func FinishedPartUploadCount(v int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldFinishedPartUploadCount, v))
}

// FolderName applies equality check predicate on the "folderName" field. It's identical to FolderNameEQ.
func FolderName(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldFolderName, v))
}

// CommittedPartCount applies equality check predicate on the "committedPartCount" field. It's identical to CommittedPartCountEQ.
func CommittedPartCount(v int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCommittedPartCount, v))
}

// TupleHash applies equality check predicate on the "tupleHash" field. It's identical to TupleHashEQ.
func TupleHash(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldTupleHash, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldKey, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldVersion, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldScope, v))
}

// RepoIdEQ applies the EQ predicate on the "repoId" field.
func RepoIdEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldRepoId, v))
}

// RepoIdNEQ applies the NEQ predicate on the "repoId" field.
func RepoIdNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldRepoId, v))
}

// RepoIdIn applies the In predicate on the "repoId" field.
func RepoIdIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldRepoId, vs...))
}

// RepoIdNotIn applies the NotIn predicate on the "repoId" field.
func RepoIdNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldRepoId, vs...))
}

// RepoIdGT applies the GT predicate on the "repoId" field.
func RepoIdGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldRepoId, v))
}

// RepoIdGTE applies the GTE predicate on the "repoId" field.
func RepoIdGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldRepoId, v))
}

// RepoIdLT applies the LT predicate on the "repoId" field.
func RepoIdLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldRepoId, v))
}

// RepoIdLTE applies the LTE predicate on the "repoId" field.
func RepoIdLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldRepoId, v))
}

// RepoIdContains applies the Contains predicate on the "repoId" field.
func RepoIdContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldRepoId, v))
}

// RepoIdHasPrefix applies the HasPrefix predicate on the "repoId" field.
func RepoIdHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldRepoId, v))
}

// RepoIdHasSuffix applies the HasSuffix predicate on the "repoId" field.
func RepoIdHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldRepoId, v))
}

// RepoIdEqualFold applies the EqualFold predicate on the "repoId" field.
func RepoIdEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldRepoId, v))
}

// RepoIdContainsFold applies the ContainsFold predicate on the "repoId" field.
func RepoIdContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldRepoId, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...int64) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...int64) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldCreatedAt, v))
}

// LastPartUploadedAtEQ applies the EQ predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtEQ(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldLastPartUploadedAt, v))
}

// LastPartUploadedAtNEQ applies the NEQ predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtNEQ(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldLastPartUploadedAt, v))
}

// LastPartUploadedAtIn applies the In predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtIn(vs ...int64) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldLastPartUploadedAt, vs...))
}

// LastPartUploadedAtNotIn applies the NotIn predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtNotIn(vs ...int64) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldLastPartUploadedAt, vs...))
}

// LastPartUploadedAtGT applies the GT predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtGT(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldLastPartUploadedAt, v))
}

// LastPartUploadedAtGTE applies the GTE predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtGTE(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldLastPartUploadedAt, v))
}

// LastPartUploadedAtLT applies the LT predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtLT(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldLastPartUploadedAt, v))
}

// LastPartUploadedAtLTE applies the LTE predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtLTE(v int64) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldLastPartUploadedAt, v))
}

// LastPartUploadedAtIsNil applies the IsNil predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtIsNil() predicate.Upload {
	return predicate.Upload(sql.FieldIsNull(FieldLastPartUploadedAt))
}

// LastPartUploadedAtNotNil applies the NotNil predicate on the "lastPartUploadedAt" field.
func LastPartUploadedAtNotNil() predicate.Upload {
	return predicate.Upload(sql.FieldNotNull(FieldLastPartUploadedAt))
}

// StartedPartUploadCountEQ applies the EQ predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountEQ(v int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldStartedPartUploadCount, v))
}

// StartedPartUploadCountNEQ applies the NEQ predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountNEQ(v int) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldStartedPartUploadCount, v))
}

// StartedPartUploadCountIn applies the In predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountIn(vs ...int) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldStartedPartUploadCount, vs...))
}

// StartedPartUploadCountNotIn applies the NotIn predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountNotIn(vs ...int) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldStartedPartUploadCount, vs...))
}

// StartedPartUploadCountGT applies the GT predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountGT(v int) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldStartedPartUploadCount, v))
}

// StartedPartUploadCountGTE applies the GTE predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountGTE(v int) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldStartedPartUploadCount, v))
}

// StartedPartUploadCountLT applies the LT predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountLT(v int) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldStartedPartUploadCount, v))
}

// StartedPartUploadCountLTE applies the LTE predicate on the "startedPartUploadCount" field.
func StartedPartUploadCountLTE(v int) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldStartedPartUploadCount, v))
}

// FinishedPartUploadCountEQ applies the EQ predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountEQ(v int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldFinishedPartUploadCount, v))
}

// FinishedPartUploadCountNEQ applies the NEQ predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountNEQ(v int) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldFinishedPartUploadCount, v))
}

// FinishedPartUploadCountIn applies the In predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountIn(vs ...int) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldFinishedPartUploadCount, vs...))
}

// FinishedPartUploadCountNotIn applies the NotIn predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountNotIn(vs ...int) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldFinishedPartUploadCount, vs...))
}

// FinishedPartUploadCountGT applies the GT predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountGT(v int) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldFinishedPartUploadCount, v))
}

// FinishedPartUploadCountGTE applies the GTE predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountGTE(v int) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldFinishedPartUploadCount, v))
}

// FinishedPartUploadCountLT applies the LT predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountLT(v int) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldFinishedPartUploadCount, v))
}

// FinishedPartUploadCountLTE applies the LTE predicate on the "finishedPartUploadCount" field.
func FinishedPartUploadCountLTE(v int) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldFinishedPartUploadCount, v))
}

// FolderNameEQ applies the EQ predicate on the "folderName" field.
func FolderNameEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldFolderName, v))
}

// FolderNameNEQ applies the NEQ predicate on the "folderName" field.
func FolderNameNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldFolderName, v))
}

// FolderNameIn applies the In predicate on the "folderName" field.
func FolderNameIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldFolderName, vs...))
}

// FolderNameNotIn applies the NotIn predicate on the "folderName" field.
func FolderNameNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldFolderName, vs...))
}

// FolderNameGT applies the GT predicate on the "folderName" field.
func FolderNameGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldFolderName, v))
}

// FolderNameGTE applies the GTE predicate on the "folderName" field.
func FolderNameGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldFolderName, v))
}

// FolderNameLT applies the LT predicate on the "folderName" field.
func FolderNameLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldFolderName, v))
}

// FolderNameLTE applies the LTE predicate on the "folderName" field.
func FolderNameLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldFolderName, v))
}

// FolderNameContains applies the Contains predicate on the "folderName" field.
func FolderNameContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldFolderName, v))
}

// FolderNameHasPrefix applies the HasPrefix predicate on the "folderName" field.
func FolderNameHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldFolderName, v))
}

// FolderNameHasSuffix applies the HasSuffix predicate on the "folderName" field.
func FolderNameHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldFolderName, v))
}

// FolderNameEqualFold applies the EqualFold predicate on the "folderName" field.
func FolderNameEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldFolderName, v))
}

// FolderNameContainsFold applies the ContainsFold predicate on the "folderName" field.
func FolderNameContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldFolderName, v))
}

// CommittedPartCountEQ applies the EQ predicate on the "committedPartCount" field.
func CommittedPartCountEQ(v int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCommittedPartCount, v))
}

// CommittedPartCountNEQ applies the NEQ predicate on the "committedPartCount" field.
func CommittedPartCountNEQ(v int) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldCommittedPartCount, v))
}

// CommittedPartCountIn applies the In predicate on the "committedPartCount" field.
func CommittedPartCountIn(vs ...int) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldCommittedPartCount, vs...))
}

// CommittedPartCountNotIn applies the NotIn predicate on the "committedPartCount" field.
func CommittedPartCountNotIn(vs ...int) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldCommittedPartCount, vs...))
}

// CommittedPartCountGT applies the GT predicate on the "committedPartCount" field.
func CommittedPartCountGT(v int) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldCommittedPartCount, v))
}

// CommittedPartCountGTE applies the GTE predicate on the "committedPartCount" field.
func CommittedPartCountGTE(v int) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldCommittedPartCount, v))
}

// CommittedPartCountLT applies the LT predicate on the "committedPartCount" field.
func CommittedPartCountLT(v int) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldCommittedPartCount, v))
}

// CommittedPartCountLTE applies the LTE predicate on the "committedPartCount" field.
func CommittedPartCountLTE(v int) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldCommittedPartCount, v))
}

// CommittedPartCountIsNil applies the IsNil predicate on the "committedPartCount" field.
func CommittedPartCountIsNil() predicate.Upload {
	return predicate.Upload(sql.FieldIsNull(FieldCommittedPartCount))
}

// CommittedPartCountNotNil applies the NotNil predicate on the "committedPartCount" field.
func CommittedPartCountNotNil() predicate.Upload {
	return predicate.Upload(sql.FieldNotNull(FieldCommittedPartCount))
}

// TupleHashEQ applies the EQ predicate on the "tupleHash" field.
func TupleHashEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldTupleHash, v))
}

// TupleHashNEQ applies the NEQ predicate on the "tupleHash" field.
func TupleHashNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldTupleHash, v))
}

// TupleHashIn applies the In predicate on the "tupleHash" field.
func TupleHashIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldTupleHash, vs...))
}

// TupleHashNotIn applies the NotIn predicate on the "tupleHash" field.
func TupleHashNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldTupleHash, vs...))
}

// TupleHashGT applies the GT predicate on the "tupleHash" field.
func TupleHashGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldTupleHash, v))
}

// TupleHashGTE applies the GTE predicate on the "tupleHash" field.
func TupleHashGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldTupleHash, v))
}

// TupleHashLT applies the LT predicate on the "tupleHash" field.
func TupleHashLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldTupleHash, v))
}

// TupleHashLTE applies the LTE predicate on the "tupleHash" field.
func TupleHashLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldTupleHash, v))
}

// TupleHashContains applies the Contains predicate on the "tupleHash" field.
func TupleHashContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldTupleHash, v))
}

// TupleHashHasPrefix applies the HasPrefix predicate on the "tupleHash" field.
func TupleHashHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldTupleHash, v))
}

// TupleHashHasSuffix applies the HasSuffix predicate on the "tupleHash" field.
func TupleHashHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldTupleHash, v))
}

// TupleHashIsNil applies the IsNil predicate on the "tupleHash" field.
func TupleHashIsNil() predicate.Upload {
	return predicate.Upload(sql.FieldIsNull(FieldTupleHash))
}

// TupleHashNotNil applies the NotNil predicate on the "tupleHash" field.
func TupleHashNotNil() predicate.Upload {
	return predicate.Upload(sql.FieldNotNull(FieldTupleHash))
}

// TupleHashEqualFold applies the EqualFold predicate on the "tupleHash" field.
func TupleHashEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldTupleHash, v))
}

// TupleHashContainsFold applies the ContainsFold predicate on the "tupleHash" field.
func TupleHashContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldTupleHash, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Upload) predicate.Upload {
	return predicate.Upload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Upload) predicate.Upload {
	return predicate.Upload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Upload) predicate.Upload {
	return predicate.Upload(sql.NotPredicates(p))
}
