// Code generated by ent, DO NOT EDIT.

package cacheentry

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContainsFold(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldKey, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldVersion, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldScope, v))
}

// RepoId applies equality check predicate on the "repoId" field. It's identical to RepoIdEQ.
func RepoId(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldRepoId, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// LocationId applies equality check predicate on the "locationId" field. It's identical to LocationIdEQ.
func LocationId(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldLocationId, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContainsFold(FieldKey, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContainsFold(FieldVersion, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContainsFold(FieldScope, v))
}

// RepoIdEQ applies the EQ predicate on the "repoId" field.
func RepoIdEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldRepoId, v))
}

// RepoIdNEQ applies the NEQ predicate on the "repoId" field.
func RepoIdNEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNEQ(FieldRepoId, v))
}

// RepoIdIn applies the In predicate on the "repoId" field.
func RepoIdIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldIn(FieldRepoId, vs...))
}

// RepoIdNotIn applies the NotIn predicate on the "repoId" field.
func RepoIdNotIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNotIn(FieldRepoId, vs...))
}

// RepoIdGT applies the GT predicate on the "repoId" field.
func RepoIdGT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGT(FieldRepoId, v))
}

// RepoIdGTE applies the GTE predicate on the "repoId" field.
func RepoIdGTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGTE(FieldRepoId, v))
}

// RepoIdLT applies the LT predicate on the "repoId" field.
func RepoIdLT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLT(FieldRepoId, v))
}

// RepoIdLTE applies the LTE predicate on the "repoId" field.
func RepoIdLTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLTE(FieldRepoId, v))
}

// RepoIdContains applies the Contains predicate on the "repoId" field.
func RepoIdContains(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContains(FieldRepoId, v))
}

// RepoIdHasPrefix applies the HasPrefix predicate on the "repoId" field.
func RepoIdHasPrefix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasPrefix(FieldRepoId, v))
}

// RepoIdHasSuffix applies the HasSuffix predicate on the "repoId" field.
func RepoIdHasSuffix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasSuffix(FieldRepoId, v))
}

// RepoIdEqualFold applies the EqualFold predicate on the "repoId" field.
func RepoIdEqualFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEqualFold(FieldRepoId, v))
}

// RepoIdContainsFold applies the ContainsFold predicate on the "repoId" field.
func RepoIdContainsFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContainsFold(FieldRepoId, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v int64) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// LocationIdEQ applies the EQ predicate on the "locationId" field.
func LocationIdEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEQ(FieldLocationId, v))
}

// LocationIdNEQ applies the NEQ predicate on the "locationId" field.
func LocationIdNEQ(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNEQ(FieldLocationId, v))
}

// LocationIdIn applies the In predicate on the "locationId" field.
func LocationIdIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldIn(FieldLocationId, vs...))
}

// LocationIdNotIn applies the NotIn predicate on the "locationId" field.
func LocationIdNotIn(vs ...string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldNotIn(FieldLocationId, vs...))
}

// LocationIdGT applies the GT predicate on the "locationId" field.
func LocationIdGT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGT(FieldLocationId, v))
}

// LocationIdGTE applies the GTE predicate on the "locationId" field.
func LocationIdGTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldGTE(FieldLocationId, v))
}

// LocationIdLT applies the LT predicate on the "locationId" field.
func LocationIdLT(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLT(FieldLocationId, v))
}

// LocationIdLTE applies the LTE predicate on the "locationId" field.
func LocationIdLTE(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldLTE(FieldLocationId, v))
}

// LocationIdContains applies the Contains predicate on the "locationId" field.
func LocationIdContains(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContains(FieldLocationId, v))
}

// LocationIdHasPrefix applies the HasPrefix predicate on the "locationId" field.
func LocationIdHasPrefix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasPrefix(FieldLocationId, v))
}

// LocationIdHasSuffix applies the HasSuffix predicate on the "locationId" field.
func LocationIdHasSuffix(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldHasSuffix(FieldLocationId, v))
}

// LocationIdEqualFold applies the EqualFold predicate on the "locationId" field.
func LocationIdEqualFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldEqualFold(FieldLocationId, v))
}

// LocationIdContainsFold applies the ContainsFold predicate on the "locationId" field.
func LocationIdContainsFold(v string) predicate.CacheEntry {
	return predicate.CacheEntry(sql.FieldContainsFold(FieldLocationId, v))
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.CacheEntry {
	return predicate.CacheEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.StorageLocation) predicate.CacheEntry {
	return predicate.CacheEntry(func(s *sql.Selector) {
		step := newLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CacheEntry) predicate.CacheEntry {
	return predicate.CacheEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CacheEntry) predicate.CacheEntry {
	return predicate.CacheEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CacheEntry) predicate.CacheEntry {
	return predicate.CacheEntry(sql.NotPredicates(p))
}
