// Code generated by ent, DO NOT EDIT.

package storagereaderlease

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the storagereaderlease type in the database.
	Label = "storage_reader_lease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStorageLocationId holds the string denoting the storagelocationid field in the database.
	FieldStorageLocationId = "storageLocationId"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldExpiresAt holds the string denoting the expiresat field in the database.
	FieldExpiresAt = "expiresAt"
	// EdgeStorageLocation holds the string denoting the storagelocation edge name in mutations.
	EdgeStorageLocation = "storageLocation"
	// Table holds the table name of the storagereaderlease in the database.
	Table = "storage_reader_leases"
	// StorageLocationTable is the table that holds the storageLocation relation/edge.
	StorageLocationTable = "storage_reader_leases"
	// StorageLocationInverseTable is the table name for the StorageLocation entity.
	// It exists in this package in order to avoid circular dependency with the "storagelocation" package.
	StorageLocationInverseTable = "storage_locations"
	// StorageLocationColumn is the table column denoting the storageLocation relation/edge.
	StorageLocationColumn = "storageLocationId"
)

// Columns holds all SQL columns for storagereaderlease fields.
var Columns = []string{
	FieldID,
	FieldStorageLocationId,
	FieldScope,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Scope defines the type for the "scope" enum field.
type Scope string

// Scope values.
const (
	ScopeParts   Scope = "parts"
	ScopeStorage Scope = "storage"
)

func (s Scope) String() string {
	return string(s)
}

// ScopeValidator is a validator for the "scope" field enum values. It is called by the builders before save.
func ScopeValidator(s Scope) error {
	switch s {
	case ScopeParts, ScopeStorage:
		return nil
	default:
		return fmt.Errorf("storagereaderlease: invalid enum value for scope field: %q", s)
	}
}

// OrderOption defines the ordering options for the StorageReaderLease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStorageLocationId orders the results by the storageLocationId field.
func ByStorageLocationId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageLocationId, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expiresAt field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStorageLocationField orders the results by storageLocation field.
func ByStorageLocationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStorageLocationStep(), sql.OrderByField(field, opts...))
	}
}
func newStorageLocationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StorageLocationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StorageLocationTable, StorageLocationColumn),
	)
}
