// Code generated by ent, DO NOT EDIT.

package storagereaderlease

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldContainsFold(FieldID, id))
}

// StorageLocationId applies equality check predicate on the "storageLocationId" field. It's identical to StorageLocationIdEQ.
func StorageLocationId(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEQ(FieldStorageLocationId, v))
}

// ExpiresAt applies equality check predicate on the "expiresAt" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEQ(FieldExpiresAt, v))
}

// StorageLocationIdEQ applies the EQ predicate on the "storageLocationId" field.
func StorageLocationIdEQ(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEQ(FieldStorageLocationId, v))
}

// StorageLocationIdNEQ applies the NEQ predicate on the "storageLocationId" field.
func StorageLocationIdNEQ(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNEQ(FieldStorageLocationId, v))
}

// StorageLocationIdIn applies the In predicate on the "storageLocationId" field.
func StorageLocationIdIn(vs ...string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldIn(FieldStorageLocationId, vs...))
}

// StorageLocationIdNotIn applies the NotIn predicate on the "storageLocationId" field.
func StorageLocationIdNotIn(vs ...string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNotIn(FieldStorageLocationId, vs...))
}

// StorageLocationIdGT applies the GT predicate on the "storageLocationId" field.
func StorageLocationIdGT(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldGT(FieldStorageLocationId, v))
}

// StorageLocationIdGTE applies the GTE predicate on the "storageLocationId" field.
func StorageLocationIdGTE(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldGTE(FieldStorageLocationId, v))
}

// StorageLocationIdLT applies the LT predicate on the "storageLocationId" field.
func StorageLocationIdLT(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldLT(FieldStorageLocationId, v))
}

// StorageLocationIdLTE applies the LTE predicate on the "storageLocationId" field.
func StorageLocationIdLTE(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldLTE(FieldStorageLocationId, v))
}

// StorageLocationIdContains applies the Contains predicate on the "storageLocationId" field.
func StorageLocationIdContains(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldContains(FieldStorageLocationId, v))
}

// StorageLocationIdHasPrefix applies the HasPrefix predicate on the "storageLocationId" field.
func StorageLocationIdHasPrefix(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldHasPrefix(FieldStorageLocationId, v))
}

// StorageLocationIdHasSuffix applies the HasSuffix predicate on the "storageLocationId" field.
func StorageLocationIdHasSuffix(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldHasSuffix(FieldStorageLocationId, v))
}

// StorageLocationIdEqualFold applies the EqualFold predicate on the "storageLocationId" field.
func StorageLocationIdEqualFold(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEqualFold(FieldStorageLocationId, v))
}

// StorageLocationIdContainsFold applies the ContainsFold predicate on the "storageLocationId" field.
func StorageLocationIdContainsFold(v string) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldContainsFold(FieldStorageLocationId, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v Scope) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v Scope) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...Scope) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...Scope) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNotIn(FieldScope, vs...))
}

// ExpiresAtEQ applies the EQ predicate on the "expiresAt" field.
func ExpiresAtEQ(v int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expiresAt" field.
func ExpiresAtNEQ(v int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expiresAt" field.
func ExpiresAtIn(vs ...int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expiresAt" field.
func ExpiresAtNotIn(vs ...int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expiresAt" field.
func ExpiresAtGT(v int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expiresAt" field.
func ExpiresAtGTE(v int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expiresAt" field.
func ExpiresAtLT(v int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expiresAt" field.
func ExpiresAtLTE(v int64) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.FieldLTE(FieldExpiresAt, v))
}

// HasStorageLocation applies the HasEdge predicate on the "storageLocation" edge.
func HasStorageLocation() predicate.StorageReaderLease {
	return predicate.StorageReaderLease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StorageLocationTable, StorageLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStorageLocationWith applies the HasEdge predicate on the "storageLocation" edge with a given conditions (other predicates).
func HasStorageLocationWith(preds ...predicate.StorageLocation) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(func(s *sql.Selector) {
		step := newStorageLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StorageReaderLease) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StorageReaderLease) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StorageReaderLease) predicate.StorageReaderLease {
	return predicate.StorageReaderLease(sql.NotPredicates(p))
}
