// Code generated by ent, DO NOT EDIT.

package storagedeletion

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the storagedeletion type in the database.
	Label = "storage_deletion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFolderName holds the string denoting the foldername field in the database.
	FieldFolderName = "folderName"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// FieldAttemptCount holds the string denoting the attemptcount field in the database.
	FieldAttemptCount = "attemptCount"
	// FieldLastAttemptedAt holds the string denoting the lastattemptedat field in the database.
	FieldLastAttemptedAt = "lastAttemptedAt"
	// FieldLastError holds the string denoting the lasterror field in the database.
	FieldLastError = "lastError"
	// Table holds the table name of the storagedeletion in the database.
	Table = "storage_deletions"
)

// Columns holds all SQL columns for storagedeletion fields.
var Columns = []string{
	FieldID,
	FieldFolderName,
	FieldCreatedAt,
	FieldAttemptCount,
	FieldLastAttemptedAt,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FolderNameValidator is a validator for the "folderName" field. It is called by the builders before save.
	FolderNameValidator func(string) error
	// DefaultAttemptCount holds the default value on creation for the "attemptCount" field.
	DefaultAttemptCount int
	// AttemptCountValidator is a validator for the "attemptCount" field. It is called by the builders before save.
	AttemptCountValidator func(int) error
)

// OrderOption defines the ordering options for the StorageDeletion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFolderName orders the results by the folderName field.
func ByFolderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFolderName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attemptCount field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByLastAttemptedAt orders the results by the lastAttemptedAt field.
func ByLastAttemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAttemptedAt, opts...).ToFunc()
}

// ByLastError orders the results by the lastError field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}
