// Code generated by ent, DO NOT EDIT.

package storagedeletion

import (
	"entgo.io/ent/dialect/sql"
	"github.com/MxOrbit/GitHubActionCacheServer/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLTE(FieldID, id))
}

// FolderName applies equality check predicate on the "folderName" field. It's identical to FolderNameEQ.
func FolderName(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldFolderName, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldCreatedAt, v))
}

// AttemptCount applies equality check predicate on the "attemptCount" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldAttemptCount, v))
}

// LastAttemptedAt applies equality check predicate on the "lastAttemptedAt" field. It's identical to LastAttemptedAtEQ.
func LastAttemptedAt(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldLastAttemptedAt, v))
}

// LastError applies equality check predicate on the "lastError" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldLastError, v))
}

// FolderNameEQ applies the EQ predicate on the "folderName" field.
func FolderNameEQ(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldFolderName, v))
}

// FolderNameNEQ applies the NEQ predicate on the "folderName" field.
func FolderNameNEQ(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNEQ(FieldFolderName, v))
}

// FolderNameIn applies the In predicate on the "folderName" field.
func FolderNameIn(vs ...string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIn(FieldFolderName, vs...))
}

// FolderNameNotIn applies the NotIn predicate on the "folderName" field.
func FolderNameNotIn(vs ...string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotIn(FieldFolderName, vs...))
}

// FolderNameGT applies the GT predicate on the "folderName" field.
func FolderNameGT(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGT(FieldFolderName, v))
}

// FolderNameGTE applies the GTE predicate on the "folderName" field.
func FolderNameGTE(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGTE(FieldFolderName, v))
}

// FolderNameLT applies the LT predicate on the "folderName" field.
func FolderNameLT(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLT(FieldFolderName, v))
}

// FolderNameLTE applies the LTE predicate on the "folderName" field.
func FolderNameLTE(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLTE(FieldFolderName, v))
}

// FolderNameContains applies the Contains predicate on the "folderName" field.
func FolderNameContains(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldContains(FieldFolderName, v))
}

// FolderNameHasPrefix applies the HasPrefix predicate on the "folderName" field.
func FolderNameHasPrefix(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldHasPrefix(FieldFolderName, v))
}

// FolderNameHasSuffix applies the HasSuffix predicate on the "folderName" field.
func FolderNameHasSuffix(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldHasSuffix(FieldFolderName, v))
}

// FolderNameEqualFold applies the EqualFold predicate on the "folderName" field.
func FolderNameEqualFold(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEqualFold(FieldFolderName, v))
}

// FolderNameContainsFold applies the ContainsFold predicate on the "folderName" field.
func FolderNameContainsFold(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldContainsFold(FieldFolderName, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLTE(FieldCreatedAt, v))
}

// AttemptCountEQ applies the EQ predicate on the "attemptCount" field.
func AttemptCountEQ(v int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attemptCount" field.
func AttemptCountNEQ(v int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attemptCount" field.
func AttemptCountIn(vs ...int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attemptCount" field.
func AttemptCountNotIn(vs ...int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attemptCount" field.
func AttemptCountGT(v int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attemptCount" field.
func AttemptCountGTE(v int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attemptCount" field.
func AttemptCountLT(v int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attemptCount" field.
func AttemptCountLTE(v int) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLTE(FieldAttemptCount, v))
}

// LastAttemptedAtEQ applies the EQ predicate on the "lastAttemptedAt" field.
func LastAttemptedAtEQ(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldLastAttemptedAt, v))
}

// LastAttemptedAtNEQ applies the NEQ predicate on the "lastAttemptedAt" field.
func LastAttemptedAtNEQ(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNEQ(FieldLastAttemptedAt, v))
}

// LastAttemptedAtIn applies the In predicate on the "lastAttemptedAt" field.
func LastAttemptedAtIn(vs ...int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIn(FieldLastAttemptedAt, vs...))
}

// LastAttemptedAtNotIn applies the NotIn predicate on the "lastAttemptedAt" field.
func LastAttemptedAtNotIn(vs ...int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotIn(FieldLastAttemptedAt, vs...))
}

// LastAttemptedAtGT applies the GT predicate on the "lastAttemptedAt" field.
func LastAttemptedAtGT(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGT(FieldLastAttemptedAt, v))
}

// LastAttemptedAtGTE applies the GTE predicate on the "lastAttemptedAt" field.
func LastAttemptedAtGTE(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGTE(FieldLastAttemptedAt, v))
}

// LastAttemptedAtLT applies the LT predicate on the "lastAttemptedAt" field.
func LastAttemptedAtLT(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLT(FieldLastAttemptedAt, v))
}

// LastAttemptedAtLTE applies the LTE predicate on the "lastAttemptedAt" field.
func LastAttemptedAtLTE(v int64) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLTE(FieldLastAttemptedAt, v))
}

// LastAttemptedAtIsNil applies the IsNil predicate on the "lastAttemptedAt" field.
func LastAttemptedAtIsNil() predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIsNull(FieldLastAttemptedAt))
}

// LastAttemptedAtNotNil applies the NotNil predicate on the "lastAttemptedAt" field.
func LastAttemptedAtNotNil() predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotNull(FieldLastAttemptedAt))
}

// LastErrorEQ applies the EQ predicate on the "lastError" field.
func LastErrorEQ(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "lastError" field.
func LastErrorNEQ(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "lastError" field.
func LastErrorIn(vs ...string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "lastError" field.
func LastErrorNotIn(vs ...string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "lastError" field.
func LastErrorGT(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "lastError" field.
func LastErrorGTE(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "lastError" field.
func LastErrorLT(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "lastError" field.
func LastErrorLTE(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "lastError" field.
func LastErrorContains(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "lastError" field.
func LastErrorHasPrefix(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "lastError" field.
func LastErrorHasSuffix(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "lastError" field.
func LastErrorIsNil() predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "lastError" field.
func LastErrorNotNil() predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "lastError" field.
func LastErrorEqualFold(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "lastError" field.
func LastErrorContainsFold(v string) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.FieldContainsFold(FieldLastError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StorageDeletion) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StorageDeletion) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StorageDeletion) predicate.StorageDeletion {
	return predicate.StorageDeletion(sql.NotPredicates(p))
}
